"""
Alternatives API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category alternatives
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from ._base import AsyncBaseAPI, BaseAPI


class AlternativesAPI(BaseAPI):
    """Alternatives namespace: cash_flow, create, delete, get, list, nav_update, performance, summary, update."""

    def cash_flow(
        self,
        *,
        asset_id: str,
        date: str,
        flow_type: str,
        amount: float,
        description: Optional[str] = None,
        document_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Record a cash flow event (capital call, distribution) for an alternative asset

        Records a cash flow event for an alternative asset: capital call (investor pays in), distribution (fund pays out), or recallable distribution. Each event includes date, amount, type, and optional notes. Cash flows are essential for IRR/TVPI/DPI calculations. Used by advisor workflows processing fund notices.

        Args:
        asset_id: Alternative asset id receiving the cash-flow event.
        date: Cash-flow date in YYYY-MM-DD format.
        flow_type: Cash-flow type validated by the alternatives core.
        amount: Cash-flow amount; sign is normalized by type in the core.
        document_id: Optional source document id linked to the cash-flow event."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        _payload["date"] = date
        _payload["flow_type"] = flow_type
        _payload["amount"] = amount
        if description is not None:
            _payload["description"] = description
        if document_id is not None:
            _payload["document_id"] = document_id
        return self._call("alternatives.cash_flow", params=_payload, options=options, context=context)

    def create(
        self,
        *,
        name: str,
        asset_type: str,
        fund_name: Optional[str] = None,
        commitment: Optional[float] = None,
        currency: Optional[str] = "EUR",
        vintage_year: Optional[int] = None,
        manager: Optional[str] = None,
        strategy: Optional[str] = None,
        geography: Optional[str] = None,
        notes: Optional[str] = None,
        external_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a new alternative asset (PE, VC, real estate, etc.)

        Creates a new alternative asset record in the AlternativeAssets MongoDB collection. Alternative assets are illiquid investments not tracked by market data feeds: private equity, venture capital, real estate, hedge funds, infrastructure, private debt. Includes asset name, type, vintage year, committed capital, and custom metadata. Used by advisor workflows managing client allocations to alternatives.

        Args:
        asset_type: Alternative asset type validated by the alternatives core.
        fund_name: Underlying fund or vehicle name, when different from the asset name.
        commitment: Committed capital amount for the alternative investment.
        vintage_year: Fund vintage year.
        manager: Investment manager or general partner name.
        strategy: Investment strategy or mandate.
        geography: Primary investment geography.
        notes: Free-form notes stored with the asset record.
        external_id: External system identifier used for reconciliation."""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["asset_type"] = asset_type
        if fund_name is not None:
            _payload["fund_name"] = fund_name
        if commitment is not None:
            _payload["commitment"] = commitment
        if currency is not None:
            _payload["currency"] = currency
        if vintage_year is not None:
            _payload["vintage_year"] = vintage_year
        if manager is not None:
            _payload["manager"] = manager
        if strategy is not None:
            _payload["strategy"] = strategy
        if geography is not None:
            _payload["geography"] = geography
        if notes is not None:
            _payload["notes"] = notes
        if external_id is not None:
            _payload["external_id"] = external_id
        return self._call("alternatives.create", params=_payload, options=options, context=context)

    def delete(
        self,
        *,
        asset_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete an alternative asset record

        Permanently removes an alternative asset record from the AlternativeAssets MongoDB collection. Creates an audit trail entry for compliance tracking. The deletion is irreversible — all associated NAV history and cash flow records are also removed.

        Args:
        asset_id: Alternative asset id to archive."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        return self._call("alternatives.delete", params=_payload, options=options, context=context)

    def get(
        self,
        *,
        asset_id: str,
        include_cash_flows: Optional[bool] = True,
        include_nav_history: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full details for a specific alternative asset

        Returns complete alternative asset record including all NAV history entries, cash flow history, and computed performance metrics.

        Args:
        asset_id: Alternative asset id to retrieve.
        include_cash_flows: Include embedded cash-flow history in the response.
        include_nav_history: Include embedded NAV history in the response."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if include_cash_flows is not None:
            _payload["include_cash_flows"] = include_cash_flows
        if include_nav_history is not None:
            _payload["include_nav_history"] = include_nav_history
        return self._call("alternatives.get", params=_payload, options=options, context=context)

    def list(
        self,
        *,
        asset_type: Optional[str] = None,
        status: Optional[str] = None,
        search: Optional[str] = None,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        sort: Optional[str] = "createdAt",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List all alternative assets for the current user

        Returns all alternative asset records. Each entry shows name, type, vintage, committed capital, current NAV, and IRR. Used by the Dashboard alternatives portfolio view.

        Args:
        asset_type: Optional asset-type filter validated by the alternatives core.
        search: Text search applied to alternative asset records."""
        _payload: Dict[str, Any] = {}
        if asset_type is not None:
            _payload["asset_type"] = asset_type
        if status is not None:
            _payload["status"] = status
        if search is not None:
            _payload["search"] = search
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if sort is not None:
            _payload["sort"] = sort
        return self._call("alternatives.list", params=_payload, options=options, context=context, response_format=response_format)

    def nav_update(
        self,
        *,
        asset_id: str,
        date: str,
        nav: float,
        source: Optional[str] = "manual",
        document_id: Optional[str] = None,
        notes: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Record a new NAV valuation for an alternative asset

        Adds a new Net Asset Value data point to an alternative asset's valuation history. Alternative assets are valued periodically (monthly/quarterly) rather than daily. Each NAV update includes date, value, and optional notes. Automatically recalculates performance metrics. Used by advisor workflows when receiving periodic fund statements.

        Args:
        asset_id: Alternative asset id receiving the NAV update.
        date: NAV observation date in YYYY-MM-DD format.
        nav: Net asset value amount.
        source: NAV source; invalid values are normalized to manual by the core.
        document_id: Optional document id backing the NAV update.
        notes: Optional notes for the valuation update."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        _payload["date"] = date
        _payload["nav"] = nav
        if source is not None:
            _payload["source"] = source
        if document_id is not None:
            _payload["document_id"] = document_id
        if notes is not None:
            _payload["notes"] = notes
        return self._call("alternatives.nav_update", params=_payload, options=options, context=context)

    def performance(
        self,
        *,
        asset_id: str,
        as_of_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate performance metrics (IRR, TVPI, DPI) for an alternative asset

        Computes private market performance metrics from the cash flow and NAV history: IRR (Internal Rate of Return), TVPI (Total Value to Paid-In), DPI (Distributions to Paid-In), RVPI (Residual Value to Paid-In), and PME (Public Market Equivalent). These are the standard metrics for evaluating illiquid investments. Used by the Dashboard alternatives performance view.

        Args:
        asset_id: Alternative asset id for performance calculation.
        as_of_date: Optional performance calculation date in YYYY-MM-DD format."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if as_of_date is not None:
            _payload["as_of_date"] = as_of_date
        return self._call("alternatives.performance", params=_payload, options=options, context=context)

    def summary(
        self,
        *,
        asset_type: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get an aggregate summary across all alternative assets

        Returns portfolio-level statistics across all alternative assets: total committed capital, total contributions, total distributions, total current NAV, total value, TVPI, DPI, RVPI, vintage year distribution, and asset type breakdown. Used by the Dashboard alternatives overview and by reporting modules.

        Args:
        asset_type: Optional asset-type filter validated by the alternatives core."""
        _payload: Dict[str, Any] = {}
        if asset_type is not None:
            _payload["asset_type"] = asset_type
        return self._call("alternatives.summary", params=_payload, options=options, context=context)

    def update(
        self,
        *,
        asset_id: str,
        name: Optional[str] = None,
        fund_name: Optional[str] = None,
        commitment: Optional[float] = None,
        manager: Optional[str] = None,
        strategy: Optional[str] = None,
        geography: Optional[str] = None,
        notes: Optional[str] = None,
        status: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Update alternative asset details

        Modifies an existing alternative asset record. Can update name, metadata, and status. Used by the Dashboard alternatives editor.

        Args:
        asset_id: Alternative asset id to update.
        fund_name: Updated underlying fund or vehicle name.
        commitment: Updated committed capital amount.
        manager: Updated investment manager or general partner name.
        strategy: Updated investment strategy or mandate.
        geography: Updated primary investment geography.
        notes: Updated free-form notes for the asset record."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if name is not None:
            _payload["name"] = name
        if fund_name is not None:
            _payload["fund_name"] = fund_name
        if commitment is not None:
            _payload["commitment"] = commitment
        if manager is not None:
            _payload["manager"] = manager
        if strategy is not None:
            _payload["strategy"] = strategy
        if geography is not None:
            _payload["geography"] = geography
        if notes is not None:
            _payload["notes"] = notes
        if status is not None:
            _payload["status"] = status
        return self._call("alternatives.update", params=_payload, options=options, context=context)



class AsyncAlternativesAPI(AsyncBaseAPI):
    """Alternatives namespace: cash_flow, create, delete, get, list, nav_update, performance, summary, update."""

    async def cash_flow(
        self,
        *,
        asset_id: str,
        date: str,
        flow_type: str,
        amount: float,
        description: Optional[str] = None,
        document_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Record a cash flow event (capital call, distribution) for an alternative asset

        Records a cash flow event for an alternative asset: capital call (investor pays in), distribution (fund pays out), or recallable distribution. Each event includes date, amount, type, and optional notes. Cash flows are essential for IRR/TVPI/DPI calculations. Used by advisor workflows processing fund notices.

        Args:
        asset_id: Alternative asset id receiving the cash-flow event.
        date: Cash-flow date in YYYY-MM-DD format.
        flow_type: Cash-flow type validated by the alternatives core.
        amount: Cash-flow amount; sign is normalized by type in the core.
        document_id: Optional source document id linked to the cash-flow event."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        _payload["date"] = date
        _payload["flow_type"] = flow_type
        _payload["amount"] = amount
        if description is not None:
            _payload["description"] = description
        if document_id is not None:
            _payload["document_id"] = document_id
        return await self._call("alternatives.cash_flow", params=_payload, options=options, context=context)

    async def create(
        self,
        *,
        name: str,
        asset_type: str,
        fund_name: Optional[str] = None,
        commitment: Optional[float] = None,
        currency: Optional[str] = "EUR",
        vintage_year: Optional[int] = None,
        manager: Optional[str] = None,
        strategy: Optional[str] = None,
        geography: Optional[str] = None,
        notes: Optional[str] = None,
        external_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a new alternative asset (PE, VC, real estate, etc.)

        Creates a new alternative asset record in the AlternativeAssets MongoDB collection. Alternative assets are illiquid investments not tracked by market data feeds: private equity, venture capital, real estate, hedge funds, infrastructure, private debt. Includes asset name, type, vintage year, committed capital, and custom metadata. Used by advisor workflows managing client allocations to alternatives.

        Args:
        asset_type: Alternative asset type validated by the alternatives core.
        fund_name: Underlying fund or vehicle name, when different from the asset name.
        commitment: Committed capital amount for the alternative investment.
        vintage_year: Fund vintage year.
        manager: Investment manager or general partner name.
        strategy: Investment strategy or mandate.
        geography: Primary investment geography.
        notes: Free-form notes stored with the asset record.
        external_id: External system identifier used for reconciliation."""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["asset_type"] = asset_type
        if fund_name is not None:
            _payload["fund_name"] = fund_name
        if commitment is not None:
            _payload["commitment"] = commitment
        if currency is not None:
            _payload["currency"] = currency
        if vintage_year is not None:
            _payload["vintage_year"] = vintage_year
        if manager is not None:
            _payload["manager"] = manager
        if strategy is not None:
            _payload["strategy"] = strategy
        if geography is not None:
            _payload["geography"] = geography
        if notes is not None:
            _payload["notes"] = notes
        if external_id is not None:
            _payload["external_id"] = external_id
        return await self._call("alternatives.create", params=_payload, options=options, context=context)

    async def delete(
        self,
        *,
        asset_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete an alternative asset record

        Permanently removes an alternative asset record from the AlternativeAssets MongoDB collection. Creates an audit trail entry for compliance tracking. The deletion is irreversible — all associated NAV history and cash flow records are also removed.

        Args:
        asset_id: Alternative asset id to archive."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        return await self._call("alternatives.delete", params=_payload, options=options, context=context)

    async def get(
        self,
        *,
        asset_id: str,
        include_cash_flows: Optional[bool] = True,
        include_nav_history: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full details for a specific alternative asset

        Returns complete alternative asset record including all NAV history entries, cash flow history, and computed performance metrics.

        Args:
        asset_id: Alternative asset id to retrieve.
        include_cash_flows: Include embedded cash-flow history in the response.
        include_nav_history: Include embedded NAV history in the response."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if include_cash_flows is not None:
            _payload["include_cash_flows"] = include_cash_flows
        if include_nav_history is not None:
            _payload["include_nav_history"] = include_nav_history
        return await self._call("alternatives.get", params=_payload, options=options, context=context)

    async def list(
        self,
        *,
        asset_type: Optional[str] = None,
        status: Optional[str] = None,
        search: Optional[str] = None,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        sort: Optional[str] = "createdAt",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List all alternative assets for the current user

        Returns all alternative asset records. Each entry shows name, type, vintage, committed capital, current NAV, and IRR. Used by the Dashboard alternatives portfolio view.

        Args:
        asset_type: Optional asset-type filter validated by the alternatives core.
        search: Text search applied to alternative asset records."""
        _payload: Dict[str, Any] = {}
        if asset_type is not None:
            _payload["asset_type"] = asset_type
        if status is not None:
            _payload["status"] = status
        if search is not None:
            _payload["search"] = search
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if sort is not None:
            _payload["sort"] = sort
        return await self._call("alternatives.list", params=_payload, options=options, context=context, response_format=response_format)

    async def nav_update(
        self,
        *,
        asset_id: str,
        date: str,
        nav: float,
        source: Optional[str] = "manual",
        document_id: Optional[str] = None,
        notes: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Record a new NAV valuation for an alternative asset

        Adds a new Net Asset Value data point to an alternative asset's valuation history. Alternative assets are valued periodically (monthly/quarterly) rather than daily. Each NAV update includes date, value, and optional notes. Automatically recalculates performance metrics. Used by advisor workflows when receiving periodic fund statements.

        Args:
        asset_id: Alternative asset id receiving the NAV update.
        date: NAV observation date in YYYY-MM-DD format.
        nav: Net asset value amount.
        source: NAV source; invalid values are normalized to manual by the core.
        document_id: Optional document id backing the NAV update.
        notes: Optional notes for the valuation update."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        _payload["date"] = date
        _payload["nav"] = nav
        if source is not None:
            _payload["source"] = source
        if document_id is not None:
            _payload["document_id"] = document_id
        if notes is not None:
            _payload["notes"] = notes
        return await self._call("alternatives.nav_update", params=_payload, options=options, context=context)

    async def performance(
        self,
        *,
        asset_id: str,
        as_of_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate performance metrics (IRR, TVPI, DPI) for an alternative asset

        Computes private market performance metrics from the cash flow and NAV history: IRR (Internal Rate of Return), TVPI (Total Value to Paid-In), DPI (Distributions to Paid-In), RVPI (Residual Value to Paid-In), and PME (Public Market Equivalent). These are the standard metrics for evaluating illiquid investments. Used by the Dashboard alternatives performance view.

        Args:
        asset_id: Alternative asset id for performance calculation.
        as_of_date: Optional performance calculation date in YYYY-MM-DD format."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if as_of_date is not None:
            _payload["as_of_date"] = as_of_date
        return await self._call("alternatives.performance", params=_payload, options=options, context=context)

    async def summary(
        self,
        *,
        asset_type: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get an aggregate summary across all alternative assets

        Returns portfolio-level statistics across all alternative assets: total committed capital, total contributions, total distributions, total current NAV, total value, TVPI, DPI, RVPI, vintage year distribution, and asset type breakdown. Used by the Dashboard alternatives overview and by reporting modules.

        Args:
        asset_type: Optional asset-type filter validated by the alternatives core."""
        _payload: Dict[str, Any] = {}
        if asset_type is not None:
            _payload["asset_type"] = asset_type
        return await self._call("alternatives.summary", params=_payload, options=options, context=context)

    async def update(
        self,
        *,
        asset_id: str,
        name: Optional[str] = None,
        fund_name: Optional[str] = None,
        commitment: Optional[float] = None,
        manager: Optional[str] = None,
        strategy: Optional[str] = None,
        geography: Optional[str] = None,
        notes: Optional[str] = None,
        status: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Update alternative asset details

        Modifies an existing alternative asset record. Can update name, metadata, and status. Used by the Dashboard alternatives editor.

        Args:
        asset_id: Alternative asset id to update.
        fund_name: Updated underlying fund or vehicle name.
        commitment: Updated committed capital amount.
        manager: Updated investment manager or general partner name.
        strategy: Updated investment strategy or mandate.
        geography: Updated primary investment geography.
        notes: Updated free-form notes for the asset record."""
        _payload: Dict[str, Any] = {}
        _payload["asset_id"] = asset_id
        if name is not None:
            _payload["name"] = name
        if fund_name is not None:
            _payload["fund_name"] = fund_name
        if commitment is not None:
            _payload["commitment"] = commitment
        if manager is not None:
            _payload["manager"] = manager
        if strategy is not None:
            _payload["strategy"] = strategy
        if geography is not None:
            _payload["geography"] = geography
        if notes is not None:
            _payload["notes"] = notes
        if status is not None:
            _payload["status"] = status
        return await self._call("alternatives.update", params=_payload, options=options, context=context)


