"""
AssetAllocation API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category asset_allocation
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class AssetAllocationAPI(BaseAPI):
    """AssetAllocation namespace: backtest, compare, decompose, drift, frontier, optimize, risk_profile, stress, suggest_securities, validate."""

    def backtest(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        rebalance_frequency: Optional[str] = None,
        return_method: Optional[str] = "twr",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Backtest model

        Backtest model using portfolio returns engine.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        rebalance_frequency: monthly|quarterly|annual|weekly
        return_method: twr|mwr|modified_dietz"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if rebalance_frequency is not None:
            _payload["rebalance_frequency"] = rebalance_frequency
        if return_method is not None:
            _payload["return_method"] = return_method
        return self._call("asset_allocation.backtest", params=_payload, options=options, context=context, response_format=response_format)

    def compare(
        self,
        *,
        models: List[Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple models

        Backtest and compare multiple asset allocation models.

        Args:
        models: List of asset allocation models
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        metrics: Metrics to include in comparison"""
        _payload: Dict[str, Any] = {}
        _payload["models"] = models
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        return self._call("asset_allocation.compare", params=_payload, options=options, context=context, response_format=response_format)

    def decompose(
        self,
        *,
        portfolio_id: str,
        model: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Decompose portfolio by asset class

        Map portfolio securities into asset classes (or model classes).

        Args:
        portfolio_id: Portfolio ID
        model: Optional model for class mapping"""
        _payload: Dict[str, Any] = {}
        _payload["portfolio_id"] = portfolio_id
        if model is not None:
            _payload["model"] = model
        return self._call("asset_allocation.decompose", params=_payload, options=options, context=context)

    def drift(
        self,
        *,
        model: Dict[str, Any],
        portfolio_id: str,
        tolerance: Optional[float] = 0.05,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate model drift

        Compare current portfolio weights vs model target allocation.

        Args:
        model: Asset allocation model
        portfolio_id: Portfolio ID
        tolerance: Absolute drift threshold"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        _payload["portfolio_id"] = portfolio_id
        if tolerance is not None:
            _payload["tolerance"] = tolerance
        return self._call("asset_allocation.drift", params=_payload, options=options, context=context)

    def frontier(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        points: Optional[int] = 50,
        cov_method: Optional[str] = "ledoit_wolf",
        rf: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Efficient frontier

        Compute efficient frontier from model class proxies.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        points: Number of frontier points
        cov_method: sample|ledoit_wolf|oas|ewma
        rf: Risk-free rate"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if points is not None:
            _payload["points"] = points
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if rf is not None:
            _payload["rf"] = rf
        return self._call("asset_allocation.frontier", params=_payload, options=options, context=context, response_format=response_format)

    def optimize(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        objective: Optional[str] = "max_sharpe",
        target_return: Optional[float] = None,
        rf: Optional[float] = 0.0,
        cov_method: Optional[str] = "ledoit_wolf",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Optimize model allocation

        Run a single optimization for model classes and bounds.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        objective: max_sharpe|min_risk|target_return|risk_parity
        target_return: Target return for target_return objective
        rf: Risk-free rate
        cov_method: sample|ledoit_wolf|oas|ewma"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if objective is not None:
            _payload["objective"] = objective
        if target_return is not None:
            _payload["target_return"] = target_return
        if rf is not None:
            _payload["rf"] = rf
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        return self._call("asset_allocation.optimize", params=_payload, options=options, context=context)

    def risk_profile(
        self,
        *,
        risk_level: int,
        currency: Optional[str] = "EUR",
        include_proxies: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get risk profile template

        Return static model template for MiFID SRI 1-7.

        Args:
        risk_level: MiFID SRI risk level 1-7
        currency: Model currency
        include_proxies: Include suggested proxy TepiloraCodes"""
        _payload: Dict[str, Any] = {}
        _payload["risk_level"] = risk_level
        if currency is not None:
            _payload["currency"] = currency
        if include_proxies is not None:
            _payload["include_proxies"] = include_proxies
        return self._call("asset_allocation.risk_profile", params=_payload, options=options, context=context)

    def stress(
        self,
        *,
        model: Dict[str, Any],
        scenarios: Optional[Any] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Stress test model

        Apply deterministic class-level scenarios to model weights.

        Args:
        model: Asset allocation model
        scenarios: Scenario names or custom definitions; accepts list and dict custom shocks
        start_date: Start date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if scenarios is not None:
            _payload["scenarios"] = scenarios
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("asset_allocation.stress", params=_payload, options=options, context=context)

    def suggest_securities(
        self,
        *,
        model: Dict[str, Any],
        class_name: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 5,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Suggest securities by class

        Suggest securities for one or all model classes via securities.search.

        Args:
        model: Asset allocation model
        class_name: Specific class name
        filters: Optional filters for securities.search
        limit: Max suggestions per class"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if class_name is not None:
            _payload["class_name"] = class_name
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        return self._call("asset_allocation.suggest_securities", params=_payload, options=options, context=context)

    def validate(
        self,
        *,
        model: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate asset allocation model

        Validate structure, weights, and proxy availability in D_full.parquet.

        Args:
        model: Asset allocation model"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        return self._call("asset_allocation.validate", params=_payload, options=options, context=context)



class AsyncAssetAllocationAPI(AsyncBaseAPI):
    """AssetAllocation namespace: backtest, compare, decompose, drift, frontier, optimize, risk_profile, stress, suggest_securities, validate."""

    async def backtest(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        rebalance_frequency: Optional[str] = None,
        return_method: Optional[str] = "twr",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Backtest model

        Backtest model using portfolio returns engine.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        rebalance_frequency: monthly|quarterly|annual|weekly
        return_method: twr|mwr|modified_dietz"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if rebalance_frequency is not None:
            _payload["rebalance_frequency"] = rebalance_frequency
        if return_method is not None:
            _payload["return_method"] = return_method
        return await self._call("asset_allocation.backtest", params=_payload, options=options, context=context, response_format=response_format)

    async def compare(
        self,
        *,
        models: List[Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple models

        Backtest and compare multiple asset allocation models.

        Args:
        models: List of asset allocation models
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        metrics: Metrics to include in comparison"""
        _payload: Dict[str, Any] = {}
        _payload["models"] = models
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        return await self._call("asset_allocation.compare", params=_payload, options=options, context=context, response_format=response_format)

    async def decompose(
        self,
        *,
        portfolio_id: str,
        model: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Decompose portfolio by asset class

        Map portfolio securities into asset classes (or model classes).

        Args:
        portfolio_id: Portfolio ID
        model: Optional model for class mapping"""
        _payload: Dict[str, Any] = {}
        _payload["portfolio_id"] = portfolio_id
        if model is not None:
            _payload["model"] = model
        return await self._call("asset_allocation.decompose", params=_payload, options=options, context=context)

    async def drift(
        self,
        *,
        model: Dict[str, Any],
        portfolio_id: str,
        tolerance: Optional[float] = 0.05,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate model drift

        Compare current portfolio weights vs model target allocation.

        Args:
        model: Asset allocation model
        portfolio_id: Portfolio ID
        tolerance: Absolute drift threshold"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        _payload["portfolio_id"] = portfolio_id
        if tolerance is not None:
            _payload["tolerance"] = tolerance
        return await self._call("asset_allocation.drift", params=_payload, options=options, context=context)

    async def frontier(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        points: Optional[int] = 50,
        cov_method: Optional[str] = "ledoit_wolf",
        rf: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Efficient frontier

        Compute efficient frontier from model class proxies.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        points: Number of frontier points
        cov_method: sample|ledoit_wolf|oas|ewma
        rf: Risk-free rate"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if points is not None:
            _payload["points"] = points
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if rf is not None:
            _payload["rf"] = rf
        return await self._call("asset_allocation.frontier", params=_payload, options=options, context=context, response_format=response_format)

    async def optimize(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        objective: Optional[str] = "max_sharpe",
        target_return: Optional[float] = None,
        rf: Optional[float] = 0.0,
        cov_method: Optional[str] = "ledoit_wolf",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Optimize model allocation

        Run a single optimization for model classes and bounds.

        Args:
        model: Asset allocation model
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)
        objective: max_sharpe|min_risk|target_return|risk_parity
        target_return: Target return for target_return objective
        rf: Risk-free rate
        cov_method: sample|ledoit_wolf|oas|ewma"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if objective is not None:
            _payload["objective"] = objective
        if target_return is not None:
            _payload["target_return"] = target_return
        if rf is not None:
            _payload["rf"] = rf
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        return await self._call("asset_allocation.optimize", params=_payload, options=options, context=context)

    async def risk_profile(
        self,
        *,
        risk_level: int,
        currency: Optional[str] = "EUR",
        include_proxies: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get risk profile template

        Return static model template for MiFID SRI 1-7.

        Args:
        risk_level: MiFID SRI risk level 1-7
        currency: Model currency
        include_proxies: Include suggested proxy TepiloraCodes"""
        _payload: Dict[str, Any] = {}
        _payload["risk_level"] = risk_level
        if currency is not None:
            _payload["currency"] = currency
        if include_proxies is not None:
            _payload["include_proxies"] = include_proxies
        return await self._call("asset_allocation.risk_profile", params=_payload, options=options, context=context)

    async def stress(
        self,
        *,
        model: Dict[str, Any],
        scenarios: Optional[Any] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Stress test model

        Apply deterministic class-level scenarios to model weights.

        Args:
        model: Asset allocation model
        scenarios: Scenario names or custom definitions; accepts list and dict custom shocks
        start_date: Start date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if scenarios is not None:
            _payload["scenarios"] = scenarios
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("asset_allocation.stress", params=_payload, options=options, context=context)

    async def suggest_securities(
        self,
        *,
        model: Dict[str, Any],
        class_name: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 5,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Suggest securities by class

        Suggest securities for one or all model classes via securities.search.

        Args:
        model: Asset allocation model
        class_name: Specific class name
        filters: Optional filters for securities.search
        limit: Max suggestions per class"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if class_name is not None:
            _payload["class_name"] = class_name
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("asset_allocation.suggest_securities", params=_payload, options=options, context=context)

    async def validate(
        self,
        *,
        model: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate asset allocation model

        Validate structure, weights, and proxy availability in D_full.parquet.

        Args:
        model: Asset allocation model"""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        return await self._call("asset_allocation.validate", params=_payload, options=options, context=context)


