"""
AssetAllocation API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category asset_allocation
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class AssetAllocationAPI(BaseAPI):
    """AssetAllocation namespace: backtest, compare, decompose, drift, frontier, optimize, risk_profile, stress, suggest_securities, validate."""

    def backtest(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        rebalance_frequency: Optional[str] = None,
        return_method: Optional[str] = "twr",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Backtest a strategic asset allocation model over historical data

        Simulates the historical performance of an asset allocation model using ETF proxy returns. Supports configurable rebalancing frequency (monthly, quarterly, annually) and return method (TWR, Modified Dietz). Returns: cumulative return series, annualized return, volatility, Sharpe, max drawdown, and calendar year returns. Used by the Dashboard backtest view for model validation."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if rebalance_frequency is not None:
            _payload["rebalance_frequency"] = rebalance_frequency
        if return_method is not None:
            _payload["return_method"] = return_method
        return self._call("asset_allocation.backtest", params=_payload, options=options, context=context, response_format=response_format)

    def compare(
        self,
        *,
        models: List[Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple asset allocation models side by side

        Backtests and compares 2 or more asset allocation models over the same period. Returns comparative metrics (return, risk, Sharpe, max drawdown) and cumulative performance series for overlay charting. Used by the Dashboard model comparison view."""
        _payload: Dict[str, Any] = {}
        _payload["models"] = models
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        return self._call("asset_allocation.compare", params=_payload, options=options, context=context, response_format=response_format)

    def decompose(
        self,
        *,
        portfolio_id: str,
        model: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Decompose portfolio risk and return by asset class contribution

        Breaks down a portfolio's total return and risk into contributions from each asset class in the allocation model. Uses Brinson-style attribution at the asset class level. Returns: return contribution, risk contribution, diversification benefit, and marginal risk per asset class. Used by the Dashboard for the allocation attribution chart."""
        _payload: Dict[str, Any] = {}
        _payload["portfolio_id"] = portfolio_id
        if model is not None:
            _payload["model"] = model
        return self._call("asset_allocation.decompose", params=_payload, options=options, context=context)

    def drift(
        self,
        *,
        model: Dict[str, Any],
        portfolio_id: str,
        tolerance: Optional[float] = 0.05,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate weight drift from target allocation over time

        Tracks how an asset allocation model's actual weights drift from target weights over time due to differential asset class returns. Returns a time series of drift per asset class and total portfolio drift, along with suggested rebalancing triggers. Used by the Dashboard drift monitoring view and by rebalancing alert rules."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        _payload["portfolio_id"] = portfolio_id
        if tolerance is not None:
            _payload["tolerance"] = tolerance
        return self._call("asset_allocation.drift", params=_payload, options=options, context=context)

    def frontier(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        points: Optional[int] = 50,
        cov_method: Optional[str] = "ledoit_wolf",
        rf: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Generate the efficient frontier for an asset allocation model

        Computes the efficient frontier: a series of optimal portfolios ranging from minimum risk to maximum return. Returns N points (default 50) on the frontier, each with weights, expected return, and expected risk. Includes the tangency portfolio (max Sharpe) and minimum variance portfolio. Used by the Dashboard for the interactive efficient frontier chart."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if points is not None:
            _payload["points"] = points
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if rf is not None:
            _payload["rf"] = rf
        return self._call("asset_allocation.frontier", params=_payload, options=options, context=context, response_format=response_format)

    def optimize(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        objective: Optional[str] = "max_sharpe",
        target_return: Optional[float] = None,
        rf: Optional[float] = 0.0,
        cov_method: Optional[str] = "ledoit_wolf",
        solver_settings: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Optimize a strategic asset allocation model for a given objective

        Runs mean-variance optimization on an asset allocation model. Objectives: max_sharpe (maximize risk-adjusted return), min_risk (minimum variance), target_return (minimize risk for a target return), risk_parity (equal risk contribution). Returns optimal weights, expected return, expected risk, and efficient frontier position. Uses historical ETF proxy returns for estimation. Used by the Dashboard optimizer view."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if objective is not None:
            _payload["objective"] = objective
        if target_return is not None:
            _payload["target_return"] = target_return
        if rf is not None:
            _payload["rf"] = rf
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if solver_settings is not None:
            _payload["solver_settings"] = solver_settings
        return self._call("asset_allocation.optimize", params=_payload, options=options, context=context)

    def risk_profile(
        self,
        *,
        risk_level: int,
        currency: Optional[str] = "EUR",
        include_proxies: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a MiFID-aligned asset allocation template for a risk level

        Returns a pre-built strategic asset allocation template for a given MiFID risk level (1-7). Each template defines target weights across asset classes (equity, fixed income, alternatives, cash) and sub-classes, with ETF proxy suggestions. Templates are professionally designed starting points that can be customized. Used by the Dashboard asset allocation wizard for quick-start models."""
        _payload: Dict[str, Any] = {}
        _payload["risk_level"] = risk_level
        if currency is not None:
            _payload["currency"] = currency
        if include_proxies is not None:
            _payload["include_proxies"] = include_proxies
        return self._call("asset_allocation.risk_profile", params=_payload, options=options, context=context)

    def stress(
        self,
        *,
        model: Dict[str, Any],
        scenarios: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Run custom stress scenarios on an asset allocation model

        Applies user-defined stress scenarios to an asset allocation model and returns the estimated portfolio impact per scenario. Each scenario is a dict with a `name` and a `shocks` mapping asset-class name to shock (e.g. [{'name': 'mild_correction', 'shocks': {'Global Equity': -0.30, 'Euro Gov Bonds': 0.05}}]). The operation does NOT currently expose built-in scenario names — pass only custom shock dicts. For a portfolio-level stress that uses historical scenarios, see portfolio.stress."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if scenarios is not None:
            _payload["scenarios"] = scenarios
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("asset_allocation.stress", params=_payload, options=options, context=context)

    def suggest_securities(
        self,
        *,
        model: Dict[str, Any],
        class_name: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 5,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Suggest specific ETFs to implement an asset allocation model

        For each asset class slot in an allocation model, suggests specific ETFs that best track the intended exposure. Selection criteria: tracking error, TER, AUM (liquidity), domicile preference (EU UCITS), and currency. Returns ranked suggestions per slot. Used by the Dashboard to convert an abstract allocation into a tradeable portfolio."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if class_name is not None:
            _payload["class_name"] = class_name
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        return self._call("asset_allocation.suggest_securities", params=_payload, options=options, context=context)

    def validate(
        self,
        *,
        model: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate a strategic asset allocation model definition

        Validates an asset allocation model: checks that weights sum to 100%, all asset classes have ETF proxies, constraints are consistent, and the model is well-formed. Returns validation result with any errors or warnings. Must be called before optimize/backtest/frontier. Used by the Dashboard model builder as a pre-check."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        return self._call("asset_allocation.validate", params=_payload, options=options, context=context)



class AsyncAssetAllocationAPI(AsyncBaseAPI):
    """AssetAllocation namespace: backtest, compare, decompose, drift, frontier, optimize, risk_profile, stress, suggest_securities, validate."""

    async def backtest(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        rebalance_frequency: Optional[str] = None,
        return_method: Optional[str] = "twr",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Backtest a strategic asset allocation model over historical data

        Simulates the historical performance of an asset allocation model using ETF proxy returns. Supports configurable rebalancing frequency (monthly, quarterly, annually) and return method (TWR, Modified Dietz). Returns: cumulative return series, annualized return, volatility, Sharpe, max drawdown, and calendar year returns. Used by the Dashboard backtest view for model validation."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if rebalance_frequency is not None:
            _payload["rebalance_frequency"] = rebalance_frequency
        if return_method is not None:
            _payload["return_method"] = return_method
        return await self._call("asset_allocation.backtest", params=_payload, options=options, context=context, response_format=response_format)

    async def compare(
        self,
        *,
        models: List[Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple asset allocation models side by side

        Backtests and compares 2 or more asset allocation models over the same period. Returns comparative metrics (return, risk, Sharpe, max drawdown) and cumulative performance series for overlay charting. Used by the Dashboard model comparison view."""
        _payload: Dict[str, Any] = {}
        _payload["models"] = models
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        return await self._call("asset_allocation.compare", params=_payload, options=options, context=context, response_format=response_format)

    async def decompose(
        self,
        *,
        portfolio_id: str,
        model: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Decompose portfolio risk and return by asset class contribution

        Breaks down a portfolio's total return and risk into contributions from each asset class in the allocation model. Uses Brinson-style attribution at the asset class level. Returns: return contribution, risk contribution, diversification benefit, and marginal risk per asset class. Used by the Dashboard for the allocation attribution chart."""
        _payload: Dict[str, Any] = {}
        _payload["portfolio_id"] = portfolio_id
        if model is not None:
            _payload["model"] = model
        return await self._call("asset_allocation.decompose", params=_payload, options=options, context=context)

    async def drift(
        self,
        *,
        model: Dict[str, Any],
        portfolio_id: str,
        tolerance: Optional[float] = 0.05,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate weight drift from target allocation over time

        Tracks how an asset allocation model's actual weights drift from target weights over time due to differential asset class returns. Returns a time series of drift per asset class and total portfolio drift, along with suggested rebalancing triggers. Used by the Dashboard drift monitoring view and by rebalancing alert rules."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        _payload["portfolio_id"] = portfolio_id
        if tolerance is not None:
            _payload["tolerance"] = tolerance
        return await self._call("asset_allocation.drift", params=_payload, options=options, context=context)

    async def frontier(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        points: Optional[int] = 50,
        cov_method: Optional[str] = "ledoit_wolf",
        rf: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Generate the efficient frontier for an asset allocation model

        Computes the efficient frontier: a series of optimal portfolios ranging from minimum risk to maximum return. Returns N points (default 50) on the frontier, each with weights, expected return, and expected risk. Includes the tangency portfolio (max Sharpe) and minimum variance portfolio. Used by the Dashboard for the interactive efficient frontier chart."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if points is not None:
            _payload["points"] = points
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if rf is not None:
            _payload["rf"] = rf
        return await self._call("asset_allocation.frontier", params=_payload, options=options, context=context, response_format=response_format)

    async def optimize(
        self,
        *,
        model: Dict[str, Any],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        objective: Optional[str] = "max_sharpe",
        target_return: Optional[float] = None,
        rf: Optional[float] = 0.0,
        cov_method: Optional[str] = "ledoit_wolf",
        solver_settings: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Optimize a strategic asset allocation model for a given objective

        Runs mean-variance optimization on an asset allocation model. Objectives: max_sharpe (maximize risk-adjusted return), min_risk (minimum variance), target_return (minimize risk for a target return), risk_parity (equal risk contribution). Returns optimal weights, expected return, expected risk, and efficient frontier position. Uses historical ETF proxy returns for estimation. Used by the Dashboard optimizer view."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if objective is not None:
            _payload["objective"] = objective
        if target_return is not None:
            _payload["target_return"] = target_return
        if rf is not None:
            _payload["rf"] = rf
        if cov_method is not None:
            _payload["cov_method"] = cov_method
        if solver_settings is not None:
            _payload["solver_settings"] = solver_settings
        return await self._call("asset_allocation.optimize", params=_payload, options=options, context=context)

    async def risk_profile(
        self,
        *,
        risk_level: int,
        currency: Optional[str] = "EUR",
        include_proxies: Optional[bool] = True,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a MiFID-aligned asset allocation template for a risk level

        Returns a pre-built strategic asset allocation template for a given MiFID risk level (1-7). Each template defines target weights across asset classes (equity, fixed income, alternatives, cash) and sub-classes, with ETF proxy suggestions. Templates are professionally designed starting points that can be customized. Used by the Dashboard asset allocation wizard for quick-start models."""
        _payload: Dict[str, Any] = {}
        _payload["risk_level"] = risk_level
        if currency is not None:
            _payload["currency"] = currency
        if include_proxies is not None:
            _payload["include_proxies"] = include_proxies
        return await self._call("asset_allocation.risk_profile", params=_payload, options=options, context=context)

    async def stress(
        self,
        *,
        model: Dict[str, Any],
        scenarios: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Run custom stress scenarios on an asset allocation model

        Applies user-defined stress scenarios to an asset allocation model and returns the estimated portfolio impact per scenario. Each scenario is a dict with a `name` and a `shocks` mapping asset-class name to shock (e.g. [{'name': 'mild_correction', 'shocks': {'Global Equity': -0.30, 'Euro Gov Bonds': 0.05}}]). The operation does NOT currently expose built-in scenario names — pass only custom shock dicts. For a portfolio-level stress that uses historical scenarios, see portfolio.stress."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if scenarios is not None:
            _payload["scenarios"] = scenarios
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("asset_allocation.stress", params=_payload, options=options, context=context)

    async def suggest_securities(
        self,
        *,
        model: Dict[str, Any],
        class_name: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 5,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Suggest specific ETFs to implement an asset allocation model

        For each asset class slot in an allocation model, suggests specific ETFs that best track the intended exposure. Selection criteria: tracking error, TER, AUM (liquidity), domicile preference (EU UCITS), and currency. Returns ranked suggestions per slot. Used by the Dashboard to convert an abstract allocation into a tradeable portfolio."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        if class_name is not None:
            _payload["class_name"] = class_name
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("asset_allocation.suggest_securities", params=_payload, options=options, context=context)

    async def validate(
        self,
        *,
        model: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate a strategic asset allocation model definition

        Validates an asset allocation model: checks that weights sum to 100%, all asset classes have ETF proxies, constraints are consistent, and the model is well-formed. Returns validation result with any errors or warnings. Must be called before optimize/backtest/frontier. Used by the Dashboard model builder as a pre-check."""
        _payload: Dict[str, Any] = {}
        _payload["model"] = model
        return await self._call("asset_allocation.validate", params=_payload, options=options, context=context)


