"""
Attachments API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category attachments
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from ._base import AsyncBaseAPI, BaseAPI


class AttachmentsAPI(BaseAPI):
    """Attachments namespace: delete, download, info, list, read, rename, upload."""

    def delete(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete a user-owned attachment

        Deletes the authenticated user's attachment blob and its sidecar metadata. The operation first resolves ownership from context and rejects cross-user fileIds because each user can only access their own attachment directory.

        Args:
        file_id: Attachment fileId returned by attachments.upload."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return self._call("attachments.delete", params=_payload, options=options, context=context)

    def download(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Download an attachment as raw bytes

        Returns the authenticated user's attachment blob as a binary response. Unlike attachments.read, this operation supports every stored attachment MIME type and does not attempt text extraction.

        Args:
        file_id: Attachment fileId returned by attachments.upload.

        Returns:
            Raw response bytes."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return self._call_binary("attachments.download", params=_payload, options=options, context=context)

    def info(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get attachment metadata

        Returns sidecar metadata for one authenticated-user attachment and verifies that the underlying blob still exists. Access is scoped to the current user by the storage path derived from context.

        Args:
        file_id: Attachment fileId returned by attachments.upload."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return self._call("attachments.info", params=_payload, options=options, context=context)

    def list(
        self,
        *,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List user-owned attachments

        Returns paginated sidecar metadata for the authenticated user's attachments. The operation reads only JSON sidecars, not file blobs, so listing remains cheap even with large files.

        Args:
        limit: Maximum number of attachments to return.
        offset: Pagination offset."""
        _payload: Dict[str, Any] = {}
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        return self._call("attachments.list", params=_payload, options=options, context=context)

    def read(
        self,
        *,
        file_id: str,
        max_chars: Optional[int] = 20000,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Read a capped text attachment preview

        Returns a capped UTF-8 preview for text/plain and text/csv attachments owned by the authenticated user. Binary attachments such as PDF, DOCX, XLSX, PNG, and JPEG are intentionally rejected here; rich extraction belongs to a later document-processing phase.

        Args:
        file_id: Attachment fileId returned by attachments.upload.
        max_chars: Maximum number of UTF-8 characters to return in the preview."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        if max_chars is not None:
            _payload["max_chars"] = max_chars
        return self._call("attachments.read", params=_payload, options=options, context=context)

    def rename(
        self,
        *,
        file_id: str,
        name: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Rename an attachment display name

        Updates only the attachment sidecar name for the authenticated user. The physical blob name stays stable, avoiding path churn, races, and repeated sanitisation of stored paths.

        Args:
        file_id: Attachment fileId returned by attachments.upload.
        name: New user-facing filename. The physical storedName remains unchanged."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        _payload["name"] = name
        return self._call("attachments.rename", params=_payload, options=options, context=context)

    def upload(
        self,
        *,
        file: Any,
        filename: str,
        mime_type: Optional[str] = None,
        source: Optional[str] = "dashboard",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Upload a user-owned attachment

        Stores a single authenticated-user attachment in the Tepilora attachment bucket. The operation validates size, filename containment, declared MIME versus detected content, and allowed content types. It writes the blob under a stable generated fileId and stores human metadata in a JSON sidecar so list and info do not need to read file bytes.

        Args:
        file: Uploaded file payload transported as multipart/form-data.
        filename: Original user-facing filename. Path components are rejected.
        mime_type: Optional MIME type declared by the transport layer; it must match detected content.
        source: Logical source that created the attachment."""
        _payload: Dict[str, Any] = {}
        _payload["file"] = file
        _payload["filename"] = filename
        if mime_type is not None:
            _payload["mime_type"] = mime_type
        if source is not None:
            _payload["source"] = source
        return self._call_multipart("attachments.upload", params=_payload, file_fields=('file',), options=options, context=context)



class AsyncAttachmentsAPI(AsyncBaseAPI):
    """Attachments namespace: delete, download, info, list, read, rename, upload."""

    async def delete(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete a user-owned attachment

        Deletes the authenticated user's attachment blob and its sidecar metadata. The operation first resolves ownership from context and rejects cross-user fileIds because each user can only access their own attachment directory.

        Args:
        file_id: Attachment fileId returned by attachments.upload."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return await self._call("attachments.delete", params=_payload, options=options, context=context)

    async def download(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Download an attachment as raw bytes

        Returns the authenticated user's attachment blob as a binary response. Unlike attachments.read, this operation supports every stored attachment MIME type and does not attempt text extraction.

        Args:
        file_id: Attachment fileId returned by attachments.upload.

        Returns:
            Raw response bytes."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return await self._call_binary("attachments.download", params=_payload, options=options, context=context)

    async def info(
        self,
        *,
        file_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get attachment metadata

        Returns sidecar metadata for one authenticated-user attachment and verifies that the underlying blob still exists. Access is scoped to the current user by the storage path derived from context.

        Args:
        file_id: Attachment fileId returned by attachments.upload."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        return await self._call("attachments.info", params=_payload, options=options, context=context)

    async def list(
        self,
        *,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List user-owned attachments

        Returns paginated sidecar metadata for the authenticated user's attachments. The operation reads only JSON sidecars, not file blobs, so listing remains cheap even with large files.

        Args:
        limit: Maximum number of attachments to return.
        offset: Pagination offset."""
        _payload: Dict[str, Any] = {}
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        return await self._call("attachments.list", params=_payload, options=options, context=context)

    async def read(
        self,
        *,
        file_id: str,
        max_chars: Optional[int] = 20000,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Read a capped text attachment preview

        Returns a capped UTF-8 preview for text/plain and text/csv attachments owned by the authenticated user. Binary attachments such as PDF, DOCX, XLSX, PNG, and JPEG are intentionally rejected here; rich extraction belongs to a later document-processing phase.

        Args:
        file_id: Attachment fileId returned by attachments.upload.
        max_chars: Maximum number of UTF-8 characters to return in the preview."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        if max_chars is not None:
            _payload["max_chars"] = max_chars
        return await self._call("attachments.read", params=_payload, options=options, context=context)

    async def rename(
        self,
        *,
        file_id: str,
        name: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Rename an attachment display name

        Updates only the attachment sidecar name for the authenticated user. The physical blob name stays stable, avoiding path churn, races, and repeated sanitisation of stored paths.

        Args:
        file_id: Attachment fileId returned by attachments.upload.
        name: New user-facing filename. The physical storedName remains unchanged."""
        _payload: Dict[str, Any] = {}
        _payload["file_id"] = file_id
        _payload["name"] = name
        return await self._call("attachments.rename", params=_payload, options=options, context=context)

    async def upload(
        self,
        *,
        file: Any,
        filename: str,
        mime_type: Optional[str] = None,
        source: Optional[str] = "dashboard",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Upload a user-owned attachment

        Stores a single authenticated-user attachment in the Tepilora attachment bucket. The operation validates size, filename containment, declared MIME versus detected content, and allowed content types. It writes the blob under a stable generated fileId and stores human metadata in a JSON sidecar so list and info do not need to read file bytes.

        Args:
        file: Uploaded file payload transported as multipart/form-data.
        filename: Original user-facing filename. Path components are rejected.
        mime_type: Optional MIME type declared by the transport layer; it must match detected content.
        source: Logical source that created the attachment."""
        _payload: Dict[str, Any] = {}
        _payload["file"] = file
        _payload["filename"] = filename
        if mime_type is not None:
            _payload["mime_type"] = mime_type
        if source is not None:
            _payload["source"] = source
        return await self._call_multipart("attachments.upload", params=_payload, file_fields=('file',), options=options, context=context)


