"""
Data API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category data
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class DataAPI(BaseAPI):
    """Data namespace: security."""

    def security(
        self,
        *,
        identifier: str,
        fields: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get raw security data fields directly from the D parquet file

        Low-level data access that returns raw fields from the D (Description) parquet for a given security. Unlike securities.details which returns a curated subset, data.security exposes all available columns without transformation. Used for internal tooling, data quality checks, and advanced use cases requiring fields not exposed by the higher-level securities operations.

        Args:
        identifier: Single security identifier: ISIN, TepiloraCode, or Bloomberg ticker
        fields: Optional list of fields to include in the response."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if fields is not None:
            _payload["fields"] = fields
        return self._call("data.security", params=_payload, options=options, context=context)



class AsyncDataAPI(AsyncBaseAPI):
    """Data namespace: security."""

    async def security(
        self,
        *,
        identifier: str,
        fields: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get raw security data fields directly from the D parquet file

        Low-level data access that returns raw fields from the D (Description) parquet for a given security. Unlike securities.details which returns a curated subset, data.security exposes all available columns without transformation. Used for internal tooling, data quality checks, and advanced use cases requiring fields not exposed by the higher-level securities operations.

        Args:
        identifier: Single security identifier: ISIN, TepiloraCode, or Bloomberg ticker
        fields: Optional list of fields to include in the response."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if fields is not None:
            _payload["fields"] = fields
        return await self._call("data.security", params=_payload, options=options, context=context)


