"""
Esg API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category esg
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class EsgAPI(BaseAPI):
    """Esg namespace: compare, get, portfolio, screen, summary."""

    def compare(
        self,
        *,
        portfolios: List[Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Compare ESG profiles of multiple securities side by side

        Returns a comparison table of ESG metrics for 2 or more securities. Each security shows overall ESG score, E/S/G pillar scores, controversy level, carbon intensity, and SFDR classification. Enables visual comparison for security selection based on sustainability criteria. Used by the Dashboard comparison view ESG tab."""
        _payload: Dict[str, Any] = {}
        _payload["portfolios"] = portfolios
        return self._call("esg.compare", params=_payload, options=options, context=context)

    def get(
        self,
        *,
        identifiers: Union[str, List[str]],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get ESG scores and ratings for a security

        Returns Environmental, Social, and Governance (ESG) scores for a security. Includes overall ESG score, individual E/S/G pillar scores, controversy flags, carbon intensity, and ESG risk rating. Used by the Dashboard ESG tab and by portfolio ESG analysis."""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        return self._call("esg.get", params=_payload, options=options, context=context)

    def portfolio(
        self,
        *,
        portfolio_id: Optional[str] = None,
        weights: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate aggregate ESG metrics for a portfolio

        Computes weighted-average ESG scores across all holdings in a portfolio. Accepts portfolio_id (auto-resolves weights from saved portfolio) or explicit weights dict. Returns portfolio-level ESG score, pillar breakdown, carbon footprint, controversy exposure, and SFDR alignment metrics. Used by the Dashboard portfolio ESG view and by reporting modules for ESG disclosure."""
        _payload: Dict[str, Any] = {}
        if portfolio_id is not None:
            _payload["portfolio_id"] = portfolio_id
        if weights is not None:
            _payload["weights"] = weights
        return self._call("esg.portfolio", params=_payload, options=options, context=context)

    def screen(
        self,
        *,
        criteria: Optional[Dict[str, Any]] = None,
        universe: Optional[List[Any]] = None,
        min_sri: Optional[int] = None,
        max_sri: Optional[int] = None,
        min_esg_score: Optional[float] = None,
        sfdr_filter: Optional[List[Any]] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen securities by ESG criteria and exclusion filters

        Filters the securities universe by ESG criteria: minimum ESG score, pillar thresholds, controversy exclusions, sector exclusions (weapons, tobacco, gambling, fossil fuels), and SFDR article classification. Returns securities passing all ESG criteria with their scores. Used by ESG-conscious portfolio construction and by the Dashboard ESG screening view."""
        _payload: Dict[str, Any] = {}
        if criteria is not None:
            _payload["criteria"] = criteria
        if universe is not None:
            _payload["universe"] = universe
        if min_sri is not None:
            _payload["min_sri"] = min_sri
        if max_sri is not None:
            _payload["max_sri"] = max_sri
        if min_esg_score is not None:
            _payload["min_esg_score"] = min_esg_score
        if sfdr_filter is not None:
            _payload["sfdr_filter"] = sfdr_filter
        if limit is not None:
            _payload["limit"] = limit
        return self._call("esg.screen", params=_payload, options=options, context=context, response_format=response_format)

    def summary(
        self,
        *,
        identifiers: Optional[Union[str, List[str]]] = None,
        filter: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a global summary of ESG coverage across the securities catalog

        Returns an aggregate snapshot of the entire securities catalog ESG coverage: total security count, count of securities with an SRI rating, and the SRI distribution histogram (by risk-level bucket). NOTE: this operation is catalog-wide, not per-security. Any provided `identifiers` are currently ignored by the handler. To get ESG data for specific securities, use esg.get. Used by the Dashboard ESG landing page and as an availability indicator before drilling into per-security data."""
        _payload: Dict[str, Any] = {}
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if filter is not None:
            _payload["filter"] = filter
        return self._call("esg.summary", params=_payload, options=options, context=context)



class AsyncEsgAPI(AsyncBaseAPI):
    """Esg namespace: compare, get, portfolio, screen, summary."""

    async def compare(
        self,
        *,
        portfolios: List[Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Compare ESG profiles of multiple securities side by side

        Returns a comparison table of ESG metrics for 2 or more securities. Each security shows overall ESG score, E/S/G pillar scores, controversy level, carbon intensity, and SFDR classification. Enables visual comparison for security selection based on sustainability criteria. Used by the Dashboard comparison view ESG tab."""
        _payload: Dict[str, Any] = {}
        _payload["portfolios"] = portfolios
        return await self._call("esg.compare", params=_payload, options=options, context=context)

    async def get(
        self,
        *,
        identifiers: Union[str, List[str]],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get ESG scores and ratings for a security

        Returns Environmental, Social, and Governance (ESG) scores for a security. Includes overall ESG score, individual E/S/G pillar scores, controversy flags, carbon intensity, and ESG risk rating. Used by the Dashboard ESG tab and by portfolio ESG analysis."""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        return await self._call("esg.get", params=_payload, options=options, context=context)

    async def portfolio(
        self,
        *,
        portfolio_id: Optional[str] = None,
        weights: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate aggregate ESG metrics for a portfolio

        Computes weighted-average ESG scores across all holdings in a portfolio. Accepts portfolio_id (auto-resolves weights from saved portfolio) or explicit weights dict. Returns portfolio-level ESG score, pillar breakdown, carbon footprint, controversy exposure, and SFDR alignment metrics. Used by the Dashboard portfolio ESG view and by reporting modules for ESG disclosure."""
        _payload: Dict[str, Any] = {}
        if portfolio_id is not None:
            _payload["portfolio_id"] = portfolio_id
        if weights is not None:
            _payload["weights"] = weights
        return await self._call("esg.portfolio", params=_payload, options=options, context=context)

    async def screen(
        self,
        *,
        criteria: Optional[Dict[str, Any]] = None,
        universe: Optional[List[Any]] = None,
        min_sri: Optional[int] = None,
        max_sri: Optional[int] = None,
        min_esg_score: Optional[float] = None,
        sfdr_filter: Optional[List[Any]] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen securities by ESG criteria and exclusion filters

        Filters the securities universe by ESG criteria: minimum ESG score, pillar thresholds, controversy exclusions, sector exclusions (weapons, tobacco, gambling, fossil fuels), and SFDR article classification. Returns securities passing all ESG criteria with their scores. Used by ESG-conscious portfolio construction and by the Dashboard ESG screening view."""
        _payload: Dict[str, Any] = {}
        if criteria is not None:
            _payload["criteria"] = criteria
        if universe is not None:
            _payload["universe"] = universe
        if min_sri is not None:
            _payload["min_sri"] = min_sri
        if max_sri is not None:
            _payload["max_sri"] = max_sri
        if min_esg_score is not None:
            _payload["min_esg_score"] = min_esg_score
        if sfdr_filter is not None:
            _payload["sfdr_filter"] = sfdr_filter
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("esg.screen", params=_payload, options=options, context=context, response_format=response_format)

    async def summary(
        self,
        *,
        identifiers: Optional[Union[str, List[str]]] = None,
        filter: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a global summary of ESG coverage across the securities catalog

        Returns an aggregate snapshot of the entire securities catalog ESG coverage: total security count, count of securities with an SRI rating, and the SRI distribution histogram (by risk-level bucket). NOTE: this operation is catalog-wide, not per-security. Any provided `identifiers` are currently ignored by the handler. To get ESG data for specific securities, use esg.get. Used by the Dashboard ESG landing page and as an availability indicator before drilling into per-security data."""
        _payload: Dict[str, Any] = {}
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if filter is not None:
            _payload["filter"] = filter
        return await self._call("esg.summary", params=_payload, options=options, context=context)


