"""
Evolution API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category evolution
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class EvolutionAPI(BaseAPI):
    """Evolution namespace: add_comment, create, delete, delete_comment, edit, get, list, moderate, stats, timeline, transition, vote."""

    def add_comment(
        self,
        *,
        id: str,
        body: str,
        visibility: Optional[str] = "public",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Add a comment to an evolution item

        Adds a comment to an evolution item's discussion thread. Comments support visibility levels (public/internal). Used by the Dashboard evolution discussion."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["body"] = body
        if visibility is not None:
            _payload["visibility"] = visibility
        return self._call("evolution.add_comment", params=_payload, options=options, context=context)

    def create(
        self,
        *,
        title: str,
        description: str,
        type_: str,
        category: Optional[str] = "Other",
        page: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        severity: Optional[str] = "medium",
        affected_action: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a new feature request or bug report

        Creates a new evolution item (feature request, bug report, or improvement suggestion) in the Evolution MongoDB collection. Includes title, description, type (feature/bug/improvement), category, severity, affected action, and tags. Visible to all users for voting and commenting. Used by the Dashboard feedback/evolution page."""
        _payload: Dict[str, Any] = {}
        _payload["title"] = title
        _payload["description"] = description
        _payload["type"] = type_
        if category is not None:
            _payload["category"] = category
        if page is not None:
            _payload["page"] = page
        if tags is not None:
            _payload["tags"] = tags
        if severity is not None:
            _payload["severity"] = severity
        if affected_action is not None:
            _payload["affected_action"] = affected_action
        return self._call("evolution.create", params=_payload, options=options, context=context)

    def delete(
        self,
        *,
        id: str,
        reason: Optional[str] = None,
        hard: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete an evolution item

        Removes an evolution item. Supports soft delete (hide) or hard delete (permanent). Only the creator or admin can delete. Used by the Dashboard evolution management."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if reason is not None:
            _payload["reason"] = reason
        if hard is not None:
            _payload["hard"] = hard
        return self._call("evolution.delete", params=_payload, options=options, context=context)

    def delete_comment(
        self,
        *,
        id: str,
        comment_id: str,
        reason: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete a comment from an evolution item

        Removes a comment from an evolution item. Only the comment author or admin can delete. Requires a reason for audit trail."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["comment_id"] = comment_id
        if reason is not None:
            _payload["reason"] = reason
        return self._call("evolution.delete_comment", params=_payload, options=options, context=context)

    def edit(
        self,
        *,
        id: str,
        title: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Edit an evolution item's title, description, or tags

        Modifies an existing evolution item. Only the creator or admin can edit. Used by the Dashboard evolution editor."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if title is not None:
            _payload["title"] = title
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return self._call("evolution.edit", params=_payload, options=options, context=context)

    def get(
        self,
        *,
        id: str,
        include_comments: Optional[bool] = True,
        comments_limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full details for a specific evolution item

        Returns the complete evolution item with comments, vote count, status history, and admin notes. Used by the Dashboard evolution detail view."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if include_comments is not None:
            _payload["include_comments"] = include_comments
        if comments_limit is not None:
            _payload["comments_limit"] = comments_limit
        return self._call("evolution.get", params=_payload, options=options, context=context)

    def list(
        self,
        *,
        status: Optional[str] = None,
        type_: Optional[str] = None,
        category: Optional[str] = None,
        priority: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        query: Optional[str] = None,
        sort: Optional[str] = "createdAt",
        order: Optional[str] = "desc",
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        my_votes: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List evolution items with filters for type, status, and category

        Returns paginated list of evolution items. Filterable by type, status (open/in_progress/done/rejected), category, tags, priority, and free-text search. Sortable by votes, date, priority, or status. Used by the Dashboard evolution board."""
        _payload: Dict[str, Any] = {}
        if status is not None:
            _payload["status"] = status
        if type_ is not None:
            _payload["type"] = type_
        if category is not None:
            _payload["category"] = category
        if priority is not None:
            _payload["priority"] = priority
        if tags is not None:
            _payload["tags"] = tags
        if query is not None:
            _payload["query"] = query
        if sort is not None:
            _payload["sort"] = sort
        if order is not None:
            _payload["order"] = order
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if my_votes is not None:
            _payload["my_votes"] = my_votes
        return self._call("evolution.list", params=_payload, options=options, context=context, response_format=response_format)

    def moderate(
        self,
        *,
        id: str,
        priority: Optional[str] = None,
        category: Optional[str] = None,
        admin_notes: Optional[str] = None,
        resolution: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Moderate an evolution item (set priority, category, admin notes)

        Admin moderation actions on an evolution item: set priority, reassign category, add admin notes, and resolve. Used by the Dashboard admin moderation panel."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if priority is not None:
            _payload["priority"] = priority
        if category is not None:
            _payload["category"] = category
        if admin_notes is not None:
            _payload["admin_notes"] = admin_notes
        if resolution is not None:
            _payload["resolution"] = resolution
        return self._call("evolution.moderate", params=_payload, options=options, context=context)

    def stats(
        self,
        *,
        group_by: Optional[Any] = None,
        status: Optional[str] = None,
        category: Optional[str] = None,
        type_: Optional[str] = None,
        date_from: Optional[str] = None,
        date_to: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get aggregate statistics for evolution items

        Returns aggregate statistics: counts by status, type, category, and priority. Includes trend data (items created/resolved per period). Filterable by date range and category. Used by the Dashboard evolution analytics dashboard."""
        _payload: Dict[str, Any] = {}
        if group_by is not None:
            _payload["group_by"] = group_by
        if status is not None:
            _payload["status"] = status
        if category is not None:
            _payload["category"] = category
        if type_ is not None:
            _payload["type"] = type_
        if date_from is not None:
            _payload["date_from"] = date_from
        if date_to is not None:
            _payload["date_to"] = date_to
        return self._call("evolution.stats", params=_payload, options=options, context=context)

    def timeline(
        self,
        *,
        id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the activity timeline for an evolution item

        Returns the chronological activity log for a specific evolution item: creation, edits, status changes, comments, votes, and moderation actions. Each event includes timestamp, actor, and details. Used by the Dashboard evolution timeline view."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if limit is not None:
            _payload["limit"] = limit
        return self._call("evolution.timeline", params=_payload, options=options, context=context)

    def transition(
        self,
        *,
        id: str,
        status: str,
        reason: str,
        resolution: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Change the status of an evolution item (open, in_progress, done, rejected)

        Transitions an evolution item to a new status. Valid transitions follow a workflow: open -> in_progress -> done/rejected. Requires a reason and optional resolution notes. Admin only. Creates a status history entry. Used by the Dashboard evolution management."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["status"] = status
        _payload["reason"] = reason
        if resolution is not None:
            _payload["resolution"] = resolution
        return self._call("evolution.transition", params=_payload, options=options, context=context)

    def vote(
        self,
        *,
        id: str,
        action: Optional[str] = "upvote",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Vote on an evolution item (upvote or remove vote)

        Adds or removes a vote on an evolution item. Each user can vote once per item. Vote count influences priority ranking. Used by the Dashboard evolution voting interface."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if action is not None:
            _payload["action"] = action
        return self._call("evolution.vote", params=_payload, options=options, context=context)



class AsyncEvolutionAPI(AsyncBaseAPI):
    """Evolution namespace: add_comment, create, delete, delete_comment, edit, get, list, moderate, stats, timeline, transition, vote."""

    async def add_comment(
        self,
        *,
        id: str,
        body: str,
        visibility: Optional[str] = "public",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Add a comment to an evolution item

        Adds a comment to an evolution item's discussion thread. Comments support visibility levels (public/internal). Used by the Dashboard evolution discussion."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["body"] = body
        if visibility is not None:
            _payload["visibility"] = visibility
        return await self._call("evolution.add_comment", params=_payload, options=options, context=context)

    async def create(
        self,
        *,
        title: str,
        description: str,
        type_: str,
        category: Optional[str] = "Other",
        page: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        severity: Optional[str] = "medium",
        affected_action: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a new feature request or bug report

        Creates a new evolution item (feature request, bug report, or improvement suggestion) in the Evolution MongoDB collection. Includes title, description, type (feature/bug/improvement), category, severity, affected action, and tags. Visible to all users for voting and commenting. Used by the Dashboard feedback/evolution page."""
        _payload: Dict[str, Any] = {}
        _payload["title"] = title
        _payload["description"] = description
        _payload["type"] = type_
        if category is not None:
            _payload["category"] = category
        if page is not None:
            _payload["page"] = page
        if tags is not None:
            _payload["tags"] = tags
        if severity is not None:
            _payload["severity"] = severity
        if affected_action is not None:
            _payload["affected_action"] = affected_action
        return await self._call("evolution.create", params=_payload, options=options, context=context)

    async def delete(
        self,
        *,
        id: str,
        reason: Optional[str] = None,
        hard: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete an evolution item

        Removes an evolution item. Supports soft delete (hide) or hard delete (permanent). Only the creator or admin can delete. Used by the Dashboard evolution management."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if reason is not None:
            _payload["reason"] = reason
        if hard is not None:
            _payload["hard"] = hard
        return await self._call("evolution.delete", params=_payload, options=options, context=context)

    async def delete_comment(
        self,
        *,
        id: str,
        comment_id: str,
        reason: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete a comment from an evolution item

        Removes a comment from an evolution item. Only the comment author or admin can delete. Requires a reason for audit trail."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["comment_id"] = comment_id
        if reason is not None:
            _payload["reason"] = reason
        return await self._call("evolution.delete_comment", params=_payload, options=options, context=context)

    async def edit(
        self,
        *,
        id: str,
        title: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Edit an evolution item's title, description, or tags

        Modifies an existing evolution item. Only the creator or admin can edit. Used by the Dashboard evolution editor."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if title is not None:
            _payload["title"] = title
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return await self._call("evolution.edit", params=_payload, options=options, context=context)

    async def get(
        self,
        *,
        id: str,
        include_comments: Optional[bool] = True,
        comments_limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full details for a specific evolution item

        Returns the complete evolution item with comments, vote count, status history, and admin notes. Used by the Dashboard evolution detail view."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if include_comments is not None:
            _payload["include_comments"] = include_comments
        if comments_limit is not None:
            _payload["comments_limit"] = comments_limit
        return await self._call("evolution.get", params=_payload, options=options, context=context)

    async def list(
        self,
        *,
        status: Optional[str] = None,
        type_: Optional[str] = None,
        category: Optional[str] = None,
        priority: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        query: Optional[str] = None,
        sort: Optional[str] = "createdAt",
        order: Optional[str] = "desc",
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        my_votes: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List evolution items with filters for type, status, and category

        Returns paginated list of evolution items. Filterable by type, status (open/in_progress/done/rejected), category, tags, priority, and free-text search. Sortable by votes, date, priority, or status. Used by the Dashboard evolution board."""
        _payload: Dict[str, Any] = {}
        if status is not None:
            _payload["status"] = status
        if type_ is not None:
            _payload["type"] = type_
        if category is not None:
            _payload["category"] = category
        if priority is not None:
            _payload["priority"] = priority
        if tags is not None:
            _payload["tags"] = tags
        if query is not None:
            _payload["query"] = query
        if sort is not None:
            _payload["sort"] = sort
        if order is not None:
            _payload["order"] = order
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if my_votes is not None:
            _payload["my_votes"] = my_votes
        return await self._call("evolution.list", params=_payload, options=options, context=context, response_format=response_format)

    async def moderate(
        self,
        *,
        id: str,
        priority: Optional[str] = None,
        category: Optional[str] = None,
        admin_notes: Optional[str] = None,
        resolution: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Moderate an evolution item (set priority, category, admin notes)

        Admin moderation actions on an evolution item: set priority, reassign category, add admin notes, and resolve. Used by the Dashboard admin moderation panel."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if priority is not None:
            _payload["priority"] = priority
        if category is not None:
            _payload["category"] = category
        if admin_notes is not None:
            _payload["admin_notes"] = admin_notes
        if resolution is not None:
            _payload["resolution"] = resolution
        return await self._call("evolution.moderate", params=_payload, options=options, context=context)

    async def stats(
        self,
        *,
        group_by: Optional[Any] = None,
        status: Optional[str] = None,
        category: Optional[str] = None,
        type_: Optional[str] = None,
        date_from: Optional[str] = None,
        date_to: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get aggregate statistics for evolution items

        Returns aggregate statistics: counts by status, type, category, and priority. Includes trend data (items created/resolved per period). Filterable by date range and category. Used by the Dashboard evolution analytics dashboard."""
        _payload: Dict[str, Any] = {}
        if group_by is not None:
            _payload["group_by"] = group_by
        if status is not None:
            _payload["status"] = status
        if category is not None:
            _payload["category"] = category
        if type_ is not None:
            _payload["type"] = type_
        if date_from is not None:
            _payload["date_from"] = date_from
        if date_to is not None:
            _payload["date_to"] = date_to
        return await self._call("evolution.stats", params=_payload, options=options, context=context)

    async def timeline(
        self,
        *,
        id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the activity timeline for an evolution item

        Returns the chronological activity log for a specific evolution item: creation, edits, status changes, comments, votes, and moderation actions. Each event includes timestamp, actor, and details. Used by the Dashboard evolution timeline view."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("evolution.timeline", params=_payload, options=options, context=context)

    async def transition(
        self,
        *,
        id: str,
        status: str,
        reason: str,
        resolution: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Change the status of an evolution item (open, in_progress, done, rejected)

        Transitions an evolution item to a new status. Valid transitions follow a workflow: open -> in_progress -> done/rejected. Requires a reason and optional resolution notes. Admin only. Creates a status history entry. Used by the Dashboard evolution management."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        _payload["status"] = status
        _payload["reason"] = reason
        if resolution is not None:
            _payload["resolution"] = resolution
        return await self._call("evolution.transition", params=_payload, options=options, context=context)

    async def vote(
        self,
        *,
        id: str,
        action: Optional[str] = "upvote",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Vote on an evolution item (upvote or remove vote)

        Adds or removes a vote on an evolution item. Each user can vote once per item. Vote count influences priority ranking. Used by the Dashboard evolution voting interface."""
        _payload: Dict[str, Any] = {}
        _payload["id"] = id
        if action is not None:
            _payload["action"] = action
        return await self._call("evolution.vote", params=_payload, options=options, context=context)


