"""
Factors API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category factors
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from ._base import AsyncBaseAPI, BaseAPI


class FactorsAPI(BaseAPI):
    """Factors namespace: get, list, status."""

    def get(
        self,
        *,
        model: Optional[str] = "FF3",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get factor data

        Args:
        model: FF3|FF5|Carhart
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        params: Dict[str, Any] = {}
        if model is not None:
            params["model"] = model
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        return self._call("factors.get", params=params, options=options, context=context, response_format=response_format)

    def list(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available factors"""
        params: Dict[str, Any] = {}
        return self._call("factors.list", params=params, options=options, context=context)

    def status(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Factor data status

        Get factor data freshness."""
        params: Dict[str, Any] = {}
        return self._call("factors.status", params=params, options=options, context=context)



class AsyncFactorsAPI(AsyncBaseAPI):
    """Factors namespace: get, list, status."""

    async def get(
        self,
        *,
        model: Optional[str] = "FF3",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get factor data

        Args:
        model: FF3|FF5|Carhart
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        params: Dict[str, Any] = {}
        if model is not None:
            params["model"] = model
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        return await self._call("factors.get", params=params, options=options, context=context, response_format=response_format)

    async def list(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available factors"""
        params: Dict[str, Any] = {}
        return await self._call("factors.list", params=params, options=options, context=context)

    async def status(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Factor data status

        Get factor data freshness."""
        params: Dict[str, Any] = {}
        return await self._call("factors.status", params=params, options=options, context=context)


