"""
Fh API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category fh
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class FhAPI(BaseAPI):
    """Fh namespace: financials, history, info, latest, load, metrics, quality."""

    def financials(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        start_date: Optional[str] = None,
        statement: Optional[str] = "all",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get financials

        Income statement, balance sheet, cash flow.

        Args:
        identifiers: List of TepiloraCodes
        statement: income|balance|cashflow|all"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if start_date is not None:
            _payload["start_date"] = start_date
        if statement is not None:
            _payload["statement"] = statement
        return self._call("fh.financials", params=_payload, options=options, context=context, response_format=response_format)

    def history(
        self,
        *,
        identifier: str,
        columns: Optional[List[Any]] = None,
        limit: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get fundamentals history

        Historical fundamental data.

        Args:
        identifier: TepiloraCode or ISIN
        columns: Columns to return"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if columns is not None:
            _payload["columns"] = columns
        if limit is not None:
            _payload["limit"] = limit
        return self._call("fh.history", params=_payload, options=options, context=context, response_format=response_format)

    def info(
        self,
        *,
        identifier: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Column info

        Get information about available columns."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        return self._call("fh.info", params=_payload, options=options, context=context)

    def latest(
        self,
        *,
        identifiers: Union[str, List[str]],
        columns: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get latest fundamentals

        Get most recent fundamental data.

        Args:
        identifiers: List of TepiloraCodes
        columns: Columns to return"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if columns is not None:
            _payload["columns"] = columns
        return self._call("fh.latest", params=_payload, options=options, context=context, response_format=response_format)

    def load(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        columns: Optional[List[Any]] = None,
        rt_policy: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Load fundamentals

        Load fundamental data for securities.

        Args:
        identifiers: List of TepiloraCodes
        columns: Columns to load"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if columns is not None:
            _payload["columns"] = columns
        if rt_policy is not None:
            _payload["rt_policy"] = rt_policy
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("fh.load", params=_payload, options=options, context=context, response_format=response_format)

    def metrics(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        output_columns: Optional[str] = None,
        rt_policy: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get derived metrics

        Pre-calculated metrics (ROE, margins, etc.).

        Args:
        identifiers: List of TepiloraCodes
        metrics: Metric groups: margins|profitability|leverage|efficiency|growth"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        if output_columns is not None:
            _payload["output_columns"] = output_columns
        if rt_policy is not None:
            _payload["rt_policy"] = rt_policy
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("fh.metrics", params=_payload, options=options, context=context, response_format=response_format)

    def quality(
        self,
        *,
        identifiers: Union[str, List[str]],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Quality score

        Calculate quality score (0-100).

        Args:
        identifiers: List of TepiloraCodes"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        return self._call("fh.quality", params=_payload, options=options, context=context, response_format=response_format)



class AsyncFhAPI(AsyncBaseAPI):
    """Fh namespace: financials, history, info, latest, load, metrics, quality."""

    async def financials(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        start_date: Optional[str] = None,
        statement: Optional[str] = "all",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get financials

        Income statement, balance sheet, cash flow.

        Args:
        identifiers: List of TepiloraCodes
        statement: income|balance|cashflow|all"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if start_date is not None:
            _payload["start_date"] = start_date
        if statement is not None:
            _payload["statement"] = statement
        return await self._call("fh.financials", params=_payload, options=options, context=context, response_format=response_format)

    async def history(
        self,
        *,
        identifier: str,
        columns: Optional[List[Any]] = None,
        limit: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get fundamentals history

        Historical fundamental data.

        Args:
        identifier: TepiloraCode or ISIN
        columns: Columns to return"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if columns is not None:
            _payload["columns"] = columns
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("fh.history", params=_payload, options=options, context=context, response_format=response_format)

    async def info(
        self,
        *,
        identifier: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Column info

        Get information about available columns."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        return await self._call("fh.info", params=_payload, options=options, context=context)

    async def latest(
        self,
        *,
        identifiers: Union[str, List[str]],
        columns: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get latest fundamentals

        Get most recent fundamental data.

        Args:
        identifiers: List of TepiloraCodes
        columns: Columns to return"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if columns is not None:
            _payload["columns"] = columns
        return await self._call("fh.latest", params=_payload, options=options, context=context, response_format=response_format)

    async def load(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        columns: Optional[List[Any]] = None,
        rt_policy: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Load fundamentals

        Load fundamental data for securities.

        Args:
        identifiers: List of TepiloraCodes
        columns: Columns to load"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if columns is not None:
            _payload["columns"] = columns
        if rt_policy is not None:
            _payload["rt_policy"] = rt_policy
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("fh.load", params=_payload, options=options, context=context, response_format=response_format)

    async def metrics(
        self,
        *,
        identifiers: Union[str, List[str]],
        end_date: Optional[str] = None,
        metrics: Optional[List[Any]] = None,
        output_columns: Optional[str] = None,
        rt_policy: Optional[str] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get derived metrics

        Pre-calculated metrics (ROE, margins, etc.).

        Args:
        identifiers: List of TepiloraCodes
        metrics: Metric groups: margins|profitability|leverage|efficiency|growth"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if end_date is not None:
            _payload["end_date"] = end_date
        if metrics is not None:
            _payload["metrics"] = metrics
        if output_columns is not None:
            _payload["output_columns"] = output_columns
        if rt_policy is not None:
            _payload["rt_policy"] = rt_policy
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("fh.metrics", params=_payload, options=options, context=context, response_format=response_format)

    async def quality(
        self,
        *,
        identifiers: Union[str, List[str]],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Quality score

        Calculate quality score (0-100).

        Args:
        identifiers: List of TepiloraCodes"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        return await self._call("fh.quality", params=_payload, options=options, context=context, response_format=response_format)


