"""
Macro API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category macro
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class MacroAPI(BaseAPI):
    """Macro namespace: calendar, countries, history, indicators, latest, search."""

    def calendar(
        self,
        *,
        country: Optional[str] = None,
        from_date: Optional[str] = None,
        start_date: Optional[str] = None,
        to_date: Optional[str] = None,
        end_date: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the upcoming macroeconomic release calendar with scheduled dates

        Returns the schedule of upcoming macroeconomic data releases across all tracked countries and indicators. Each entry includes: indicator code, name, country, scheduled release date/time, importance level (low/medium/high), previous value, and forecast consensus. Filterable by country, importance, and date range. Differs from realtime.calendar (which shows today's events only) by providing a forward-looking schedule spanning days or weeks. Used by the Dashboard Macro page for the release calendar view and by research workflows planning around data releases.

        Args:
        country: Optional country filter for calendar events.
        from_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        start_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        to_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        end_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        limit: Maximum number of calendar events to return."""
        _payload: Dict[str, Any] = {}
        if country is not None:
            _payload["country"] = country
        if from_date is not None:
            _payload["from_date"] = from_date
        if start_date is not None:
            _payload["start_date"] = start_date
        if to_date is not None:
            _payload["to_date"] = to_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if limit is not None:
            _payload["limit"] = limit
        return self._call("macro.calendar", params=_payload, options=options, context=context, response_format=response_format)

    def countries(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List all countries with available macroeconomic data and indicator counts

        Returns the list of countries for which macroeconomic data is available, with the count of indicators per country. Each entry includes: country code (ISO 3166-1 alpha-2), country name, number of available indicators, and the categories covered. Used by the Dashboard Macro page for the country filter dropdown, by the AI assistant to determine data availability before querying specific country indicators, and as a discovery tool for understanding the geographic coverage of the macro database.

        Examples:
            >>> client.macro.countries()"""
        _payload: Dict[str, Any] = {}
        return self._call("macro.countries", params=_payload, options=options, context=context, response_format=response_format)

    def history(
        self,
        *,
        identifier: Optional[Any] = None,
        identifiers: Optional[Union[str, List[str]]] = None,
        indicator: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        limit: Optional[int] = 1000,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the historical time series for a macroeconomic indicator

        Returns the complete historical time series for a specific macroeconomic indicator identified by its code. Each data point includes: date, actual value, previous value, forecast consensus (when available), and revision flag. Supports date range filtering (start_date, end_date) and result limiting. Data frequency depends on the indicator (monthly for CPI, quarterly for GDP, etc.). The time series enables trend analysis, forecast accuracy assessment, and cross-indicator correlation studies. Used by the Dashboard Macro page for historical charts, by analytics workflows for macro factor models, and by the AI assistant for historical macro context.

        Args:
        indicator: Legacy alias for identifier; provide a macro TepiloraCode.
        start_date: Start date for time range queries (ISO 8601 YYYY-MM-DD)
        end_date: End date for time range queries (ISO 8601 YYYY-MM-DD)
        limit: Maximum number of historical rows to return.

        Examples:
            >>> client.macro.history(identifiers='MGDPQOQJAPI', limit=20)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if indicator is not None:
            _payload["indicator"] = indicator
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if limit is not None:
            _payload["limit"] = limit
        return self._call("macro.history", params=_payload, options=options, context=context, response_format=response_format)

    def indicators(
        self,
        *,
        country: Optional[str] = None,
        macro_area: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List available macroeconomic indicators with metadata and coverage

        Returns the catalog of all available macroeconomic indicators with their metadata: indicator code, name, country, category (GDP, inflation, employment, trade, central bank, PMI, housing, consumer), frequency (monthly, quarterly, annual), unit, source, and data availability range. Filterable by country and category. Each indicator includes a coverage summary showing the date range and number of data points available. Used by the Dashboard Macro page for the indicator selector, by the AI assistant to discover which macro data is available before querying specific time series, and by research workflows building macro dashboards.

        Args:
        country: Optional country filter, matched case-insensitively against the macro indicator country name.
        macro_area: Optional macro area filter such as Europe, Americas, or Asia.
        limit: Maximum number of indicator metadata rows to return.

        Examples:
            >>> client.macro.indicators(limit=10)"""
        _payload: Dict[str, Any] = {}
        if country is not None:
            _payload["country"] = country
        if macro_area is not None:
            _payload["macro_area"] = macro_area
        if limit is not None:
            _payload["limit"] = limit
        return self._call("macro.indicators", params=_payload, options=options, context=context, response_format=response_format)

    def latest(
        self,
        *,
        identifier: Optional[Any] = None,
        identifiers: Optional[Union[str, List[str]]] = None,
        indicator: Optional[str] = None,
        country: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the latest value and release details for macroeconomic indicators

        Returns the most recent data point for one or more macroeconomic indicators. Each result includes: indicator code, name, country, latest value, previous value, change, forecast consensus, actual vs. forecast surprise, release date, and next scheduled release date. Supports batch lookup of multiple indicators in a single call. Used by the Dashboard Market Snapshot page for the macro overview strip (GDP growth, CPI, unemployment at a glance), by the AI assistant for quick macro status queries, and by alert rules monitoring macro surprises.

        Args:
        indicator: Legacy alias for identifier; provide a macro TepiloraCode.
        country: Optional country filter used when no specific indicator is requested.
        limit: Maximum number of latest macro observations to return.

        Examples:
            >>> client.macro.latest(identifiers='MGDPQOQJAPI')"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if indicator is not None:
            _payload["indicator"] = indicator
        if country is not None:
            _payload["country"] = country
        if limit is not None:
            _payload["limit"] = limit
        return self._call("macro.latest", params=_payload, options=options, context=context, response_format=response_format)

    def search(
        self,
        *,
        query: str,
        country: Optional[str] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search macroeconomic indicators by name, country, or category

        Full-text search across the macroeconomic indicators catalog. Accepts free-text queries (e.g. 'US GDP', 'German inflation', 'unemployment rate') and returns matching indicators with metadata. Results include indicator code, name, country, category, frequency, and a relevance score. Used by the Dashboard Macro page search bar, by the AI assistant for natural-language macro data discovery, and as a prerequisite step before calling macro.history or macro.latest with a specific indicator code.

        Args:
        query: Case-insensitive literal search text matched against macro indicator names.
        country: Optional country filter applied after the text search.
        limit: Maximum number of matching indicator metadata rows to return."""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if country is not None:
            _payload["country"] = country
        if limit is not None:
            _payload["limit"] = limit
        return self._call("macro.search", params=_payload, options=options, context=context, response_format=response_format)



class AsyncMacroAPI(AsyncBaseAPI):
    """Macro namespace: calendar, countries, history, indicators, latest, search."""

    async def calendar(
        self,
        *,
        country: Optional[str] = None,
        from_date: Optional[str] = None,
        start_date: Optional[str] = None,
        to_date: Optional[str] = None,
        end_date: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the upcoming macroeconomic release calendar with scheduled dates

        Returns the schedule of upcoming macroeconomic data releases across all tracked countries and indicators. Each entry includes: indicator code, name, country, scheduled release date/time, importance level (low/medium/high), previous value, and forecast consensus. Filterable by country, importance, and date range. Differs from realtime.calendar (which shows today's events only) by providing a forward-looking schedule spanning days or weeks. Used by the Dashboard Macro page for the release calendar view and by research workflows planning around data releases.

        Args:
        country: Optional country filter for calendar events.
        from_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        start_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        to_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        end_date: Optional date in ISO 8601 format (YYYY-MM-DD)
        limit: Maximum number of calendar events to return."""
        _payload: Dict[str, Any] = {}
        if country is not None:
            _payload["country"] = country
        if from_date is not None:
            _payload["from_date"] = from_date
        if start_date is not None:
            _payload["start_date"] = start_date
        if to_date is not None:
            _payload["to_date"] = to_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("macro.calendar", params=_payload, options=options, context=context, response_format=response_format)

    async def countries(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List all countries with available macroeconomic data and indicator counts

        Returns the list of countries for which macroeconomic data is available, with the count of indicators per country. Each entry includes: country code (ISO 3166-1 alpha-2), country name, number of available indicators, and the categories covered. Used by the Dashboard Macro page for the country filter dropdown, by the AI assistant to determine data availability before querying specific country indicators, and as a discovery tool for understanding the geographic coverage of the macro database.

        Examples:
            >>> await client.macro.countries()"""
        _payload: Dict[str, Any] = {}
        return await self._call("macro.countries", params=_payload, options=options, context=context, response_format=response_format)

    async def history(
        self,
        *,
        identifier: Optional[Any] = None,
        identifiers: Optional[Union[str, List[str]]] = None,
        indicator: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        limit: Optional[int] = 1000,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the historical time series for a macroeconomic indicator

        Returns the complete historical time series for a specific macroeconomic indicator identified by its code. Each data point includes: date, actual value, previous value, forecast consensus (when available), and revision flag. Supports date range filtering (start_date, end_date) and result limiting. Data frequency depends on the indicator (monthly for CPI, quarterly for GDP, etc.). The time series enables trend analysis, forecast accuracy assessment, and cross-indicator correlation studies. Used by the Dashboard Macro page for historical charts, by analytics workflows for macro factor models, and by the AI assistant for historical macro context.

        Args:
        indicator: Legacy alias for identifier; provide a macro TepiloraCode.
        start_date: Start date for time range queries (ISO 8601 YYYY-MM-DD)
        end_date: End date for time range queries (ISO 8601 YYYY-MM-DD)
        limit: Maximum number of historical rows to return.

        Examples:
            >>> await client.macro.history(identifiers='MGDPQOQJAPI', limit=20)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if indicator is not None:
            _payload["indicator"] = indicator
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("macro.history", params=_payload, options=options, context=context, response_format=response_format)

    async def indicators(
        self,
        *,
        country: Optional[str] = None,
        macro_area: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """List available macroeconomic indicators with metadata and coverage

        Returns the catalog of all available macroeconomic indicators with their metadata: indicator code, name, country, category (GDP, inflation, employment, trade, central bank, PMI, housing, consumer), frequency (monthly, quarterly, annual), unit, source, and data availability range. Filterable by country and category. Each indicator includes a coverage summary showing the date range and number of data points available. Used by the Dashboard Macro page for the indicator selector, by the AI assistant to discover which macro data is available before querying specific time series, and by research workflows building macro dashboards.

        Args:
        country: Optional country filter, matched case-insensitively against the macro indicator country name.
        macro_area: Optional macro area filter such as Europe, Americas, or Asia.
        limit: Maximum number of indicator metadata rows to return.

        Examples:
            >>> await client.macro.indicators(limit=10)"""
        _payload: Dict[str, Any] = {}
        if country is not None:
            _payload["country"] = country
        if macro_area is not None:
            _payload["macro_area"] = macro_area
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("macro.indicators", params=_payload, options=options, context=context, response_format=response_format)

    async def latest(
        self,
        *,
        identifier: Optional[Any] = None,
        identifiers: Optional[Union[str, List[str]]] = None,
        indicator: Optional[str] = None,
        country: Optional[str] = None,
        limit: Optional[int] = 100,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the latest value and release details for macroeconomic indicators

        Returns the most recent data point for one or more macroeconomic indicators. Each result includes: indicator code, name, country, latest value, previous value, change, forecast consensus, actual vs. forecast surprise, release date, and next scheduled release date. Supports batch lookup of multiple indicators in a single call. Used by the Dashboard Market Snapshot page for the macro overview strip (GDP growth, CPI, unemployment at a glance), by the AI assistant for quick macro status queries, and by alert rules monitoring macro surprises.

        Args:
        indicator: Legacy alias for identifier; provide a macro TepiloraCode.
        country: Optional country filter used when no specific indicator is requested.
        limit: Maximum number of latest macro observations to return.

        Examples:
            >>> await client.macro.latest(identifiers='MGDPQOQJAPI')"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if indicator is not None:
            _payload["indicator"] = indicator
        if country is not None:
            _payload["country"] = country
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("macro.latest", params=_payload, options=options, context=context, response_format=response_format)

    async def search(
        self,
        *,
        query: str,
        country: Optional[str] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search macroeconomic indicators by name, country, or category

        Full-text search across the macroeconomic indicators catalog. Accepts free-text queries (e.g. 'US GDP', 'German inflation', 'unemployment rate') and returns matching indicators with metadata. Results include indicator code, name, country, category, frequency, and a relevance score. Used by the Dashboard Macro page search bar, by the AI assistant for natural-language macro data discovery, and as a prerequisite step before calling macro.history or macro.latest with a specific indicator code.

        Args:
        query: Case-insensitive literal search text matched against macro indicator names.
        country: Optional country filter applied after the text search.
        limit: Maximum number of matching indicator metadata rows to return."""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if country is not None:
            _payload["country"] = country
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("macro.search", params=_payload, options=options, context=context, response_format=response_format)


