"""
Options API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category options
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class OptionsAPI(BaseAPI):
    """Options namespace: greeks, iv, payoff, price, strategies, strategy."""

    def greeks(
        self,
        *,
        spot: float,
        strike: float,
        time_to_expiry: float,
        volatility: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate all option Greeks (delta, gamma, theta, vega, rho)

        Computes the full set of option sensitivity measures (Greeks) using the Black-Scholes model: Delta (price sensitivity to underlying), Gamma (delta sensitivity), Theta (time decay per day), Vega (volatility sensitivity), and Rho (interest rate sensitivity). Pure mathematical calculation. Used by the Dashboard options analysis view, by hedging workflows, and by risk management."""
        _payload: Dict[str, Any] = {}
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        _payload["volatility"] = volatility
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return self._call("options.greeks", params=_payload, options=options, context=context)

    def iv(
        self,
        *,
        market_price: float,
        spot: float,
        strike: float,
        time_to_expiry: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate implied volatility from an observed option market price

        Reverse-engineers the implied volatility from an observed market price using Newton-Raphson iteration on the Black-Scholes model. Given the market price, spot, strike, time to expiry, and risk-free rate, finds the volatility that produces the observed price. Returns implied volatility as annualized decimal. Used for volatility surface construction and by the Dashboard options analysis."""
        _payload: Dict[str, Any] = {}
        _payload["market_price"] = market_price
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return self._call("options.iv", params=_payload, options=options, context=context)

    def payoff(
        self,
        *,
        legs: List[Any],
        spot_range: Optional[float] = None,
        spot: Optional[float] = None,
        num_points: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Generate the payoff diagram data for an option or strategy at expiry

        Calculates the profit/loss at expiration across a range of underlying prices for a single option or multi-leg strategy. Returns an array of (underlying_price, payoff) pairs suitable for charting. Shows breakeven points, max profit, max loss zones. Used by the Dashboard to render interactive payoff diagrams."""
        _payload: Dict[str, Any] = {}
        _payload["legs"] = legs
        if spot_range is not None:
            _payload["spot_range"] = spot_range
        if spot is not None:
            _payload["spot"] = spot
        if num_points is not None:
            _payload["num_points"] = num_points
        return self._call("options.payoff", params=_payload, options=options, context=context)

    def price(
        self,
        *,
        spot: float,
        strike: float,
        time_to_expiry: float,
        volatility: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Price a European option using the Black-Scholes model

        Calculates the theoretical price of a European call or put option using the Black-Scholes-Merton model. Inputs: spot price (S), strike price (K), time to expiry (T in years), risk-free rate (r), volatility (sigma), and optional dividend yield. Returns option price, intrinsic value, and time value. Pure mathematical calculation — no database lookup required. Used by the Dashboard options pricer and by strategy analysis workflows."""
        _payload: Dict[str, Any] = {}
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        _payload["volatility"] = volatility
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return self._call("options.price", params=_payload, options=options, context=context)

    def strategies(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available pre-built option strategy templates

        Returns the catalog of pre-built option strategy templates with their descriptions, leg configurations, and typical use cases. Includes: covered call, protective put, bull/bear call/put spread, straddle, strangle, butterfly, iron condor, collar, and more. Each template shows the number of legs, directional bias, and risk/reward profile. Used by the Dashboard strategy selector dropdown."""
        _payload: Dict[str, Any] = {}
        return self._call("options.strategies", params=_payload, options=options, context=context)

    def strategy(
        self,
        *,
        strategy_type: str,
        spot: float,
        volatility: float,
        time_to_expiry: float,
        legs: Optional[List[Any]] = None,
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Analyze a multi-leg option strategy with combined Greeks and payoff

        Analyzes a custom multi-leg option strategy (straddle, strangle, spread, butterfly, condor, etc.). Each leg specifies option type, strike, quantity, and position (long/short). Returns combined Greeks, net premium, max profit, max loss, breakeven points, and probability of profit. Also supports named strategies via strategy_type parameter. Used by the Dashboard strategy builder."""
        _payload: Dict[str, Any] = {}
        _payload["strategy_type"] = strategy_type
        _payload["spot"] = spot
        _payload["volatility"] = volatility
        _payload["time_to_expiry"] = time_to_expiry
        if legs is not None:
            _payload["legs"] = legs
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return self._call("options.strategy", params=_payload, options=options, context=context)



class AsyncOptionsAPI(AsyncBaseAPI):
    """Options namespace: greeks, iv, payoff, price, strategies, strategy."""

    async def greeks(
        self,
        *,
        spot: float,
        strike: float,
        time_to_expiry: float,
        volatility: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate all option Greeks (delta, gamma, theta, vega, rho)

        Computes the full set of option sensitivity measures (Greeks) using the Black-Scholes model: Delta (price sensitivity to underlying), Gamma (delta sensitivity), Theta (time decay per day), Vega (volatility sensitivity), and Rho (interest rate sensitivity). Pure mathematical calculation. Used by the Dashboard options analysis view, by hedging workflows, and by risk management."""
        _payload: Dict[str, Any] = {}
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        _payload["volatility"] = volatility
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return await self._call("options.greeks", params=_payload, options=options, context=context)

    async def iv(
        self,
        *,
        market_price: float,
        spot: float,
        strike: float,
        time_to_expiry: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Calculate implied volatility from an observed option market price

        Reverse-engineers the implied volatility from an observed market price using Newton-Raphson iteration on the Black-Scholes model. Given the market price, spot, strike, time to expiry, and risk-free rate, finds the volatility that produces the observed price. Returns implied volatility as annualized decimal. Used for volatility surface construction and by the Dashboard options analysis."""
        _payload: Dict[str, Any] = {}
        _payload["market_price"] = market_price
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return await self._call("options.iv", params=_payload, options=options, context=context)

    async def payoff(
        self,
        *,
        legs: List[Any],
        spot_range: Optional[float] = None,
        spot: Optional[float] = None,
        num_points: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Generate the payoff diagram data for an option or strategy at expiry

        Calculates the profit/loss at expiration across a range of underlying prices for a single option or multi-leg strategy. Returns an array of (underlying_price, payoff) pairs suitable for charting. Shows breakeven points, max profit, max loss zones. Used by the Dashboard to render interactive payoff diagrams."""
        _payload: Dict[str, Any] = {}
        _payload["legs"] = legs
        if spot_range is not None:
            _payload["spot_range"] = spot_range
        if spot is not None:
            _payload["spot"] = spot
        if num_points is not None:
            _payload["num_points"] = num_points
        return await self._call("options.payoff", params=_payload, options=options, context=context)

    async def price(
        self,
        *,
        spot: float,
        strike: float,
        time_to_expiry: float,
        volatility: float,
        option_type: Optional[str] = "call",
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Price a European option using the Black-Scholes model

        Calculates the theoretical price of a European call or put option using the Black-Scholes-Merton model. Inputs: spot price (S), strike price (K), time to expiry (T in years), risk-free rate (r), volatility (sigma), and optional dividend yield. Returns option price, intrinsic value, and time value. Pure mathematical calculation — no database lookup required. Used by the Dashboard options pricer and by strategy analysis workflows."""
        _payload: Dict[str, Any] = {}
        _payload["spot"] = spot
        _payload["strike"] = strike
        _payload["time_to_expiry"] = time_to_expiry
        _payload["volatility"] = volatility
        if option_type is not None:
            _payload["option_type"] = option_type
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return await self._call("options.price", params=_payload, options=options, context=context)

    async def strategies(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available pre-built option strategy templates

        Returns the catalog of pre-built option strategy templates with their descriptions, leg configurations, and typical use cases. Includes: covered call, protective put, bull/bear call/put spread, straddle, strangle, butterfly, iron condor, collar, and more. Each template shows the number of legs, directional bias, and risk/reward profile. Used by the Dashboard strategy selector dropdown."""
        _payload: Dict[str, Any] = {}
        return await self._call("options.strategies", params=_payload, options=options, context=context)

    async def strategy(
        self,
        *,
        strategy_type: str,
        spot: float,
        volatility: float,
        time_to_expiry: float,
        legs: Optional[List[Any]] = None,
        risk_free_rate: Optional[float] = 0.03,
        dividend_yield: Optional[float] = 0.0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Analyze a multi-leg option strategy with combined Greeks and payoff

        Analyzes a custom multi-leg option strategy (straddle, strangle, spread, butterfly, condor, etc.). Each leg specifies option type, strike, quantity, and position (long/short). Returns combined Greeks, net premium, max profit, max loss, breakeven points, and probability of profit. Also supports named strategies via strategy_type parameter. Used by the Dashboard strategy builder."""
        _payload: Dict[str, Any] = {}
        _payload["strategy_type"] = strategy_type
        _payload["spot"] = spot
        _payload["volatility"] = volatility
        _payload["time_to_expiry"] = time_to_expiry
        if legs is not None:
            _payload["legs"] = legs
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if dividend_yield is not None:
            _payload["dividend_yield"] = dividend_yield
        return await self._call("options.strategy", params=_payload, options=options, context=context)


