"""
Profiling API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category profiling
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class ProfilingAPI(BaseAPI):
    """Profiling namespace: archive, check_suitability, convert_answers, create_profile, get_current, get_profile, list, questionnaire, update, validate_answers."""

    def archive(
        self,
        *,
        id: Optional[str] = None,
        profile_id: Optional[str] = None,
        client_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Archive a MiFID II profile (mark as no longer current)

        Marks a profile as archived, making it no longer the active profile for the linked client. Archived profiles are retained for regulatory record-keeping but excluded from suitability checks. Used when a client completes a new questionnaire.

        Args:
        profile_id: MiFID profile identifier to archive; equivalent to id when both are accepted by the handler."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if profile_id is not None:
            _payload["profile_id"] = profile_id
        if client_id is not None:
            _payload["client_id"] = client_id
        return self._call("profiling.archive", params=_payload, options=options, context=context)

    def check_suitability(
        self,
        *,
        client_id: str,
        identifiers: Optional[Union[str, List[str]]] = None,
        portfolio_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Check if a security or portfolio is suitable for a client's MiFID II profile

        Evaluates whether a specific security or portfolio allocation is suitable given the client's MiFID II profile. Compares the security's risk level (SRI), complexity, and product type against the client's risk tolerance, knowledge, and investment objectives. Returns: suitable (yes/no), warnings, reasons, and the specific MiFID II constraints that were checked. Required by European regulation before any investment recommendation. Used by the Dashboard recommendation flow and by portfolio rebalancing workflows."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if portfolio_id is not None:
            _payload["portfolio_id"] = portfolio_id
        return self._call("profiling.check_suitability", params=_payload, options=options, context=context)

    def convert_answers(
        self,
        *,
        answers: Dict[str, Any],
        language: Optional[str] = "it",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Convert raw questionnaire answers into scored profile dimensions

        Transforms raw questionnaire answers into numerical scores across MiFID II dimensions: risk tolerance (1-7), investment horizon, knowledge level, loss capacity, and investment objectives. Each dimension is scored based on the answer weighting scheme. Returns the scored dimensions ready for profile creation. Used as an intermediate step between validation and profile creation.

        Args:
        answers: Raw questionnaire answers keyed by question id.
        language: Language code used for localized score labels in the conversion output."""
        _payload: Dict[str, Any] = {}
        _payload["answers"] = answers
        if language is not None:
            _payload["language"] = language
        return self._call("profiling.convert_answers", params=_payload, options=options, context=context)

    def create_profile(
        self,
        *,
        client_id: str,
        questionnaire: Dict[str, Any],
        classification: Optional[str] = "retail",
        visibility: Optional[str] = "private",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a MiFID II investor profile from scored dimensions

        Creates a new MiFID II investor profile in the MifidProfiles MongoDB collection. Accepts scored dimensions from profiling.convert_answers and generates: risk profile category (conservative to aggressive), recommended asset allocation ranges, suitability constraints, and regulatory classification. Links to a client entity if client_id is provided. Used by the Dashboard after questionnaire completion.

        Args:
        questionnaire: Scored questionnaire profile generated from profiling.convert_answers.
        classification: Regulatory client classification used for suitability rules.
        visibility: Profile visibility scope."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        _payload["questionnaire"] = questionnaire
        if classification is not None:
            _payload["classification"] = classification
        if visibility is not None:
            _payload["visibility"] = visibility
        return self._call("profiling.create_profile", params=_payload, options=options, context=context)

    def get_current(
        self,
        *,
        client_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the current active MiFID II profile for a client

        Returns the most recent active (non-archived) MiFID II profile for a given client. A client may have multiple profiles over time but only one is current. Used by suitability checks to get the applicable profile and by the Dashboard client overview."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        return self._call("profiling.get_current", params=_payload, options=options, context=context)

    def get_profile(
        self,
        *,
        id: Optional[str] = None,
        profile_id: Optional[str] = None,
        client_id: Optional[str] = None,
        version: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a specific MiFID II profile by ID

        Returns the complete MiFID II profile: risk category, scored dimensions, recommended allocations, suitability constraints, creation date, and linked client. Used by the Dashboard profile detail view and by suitability check workflows.

        Args:
        profile_id: MiFID profile identifier to retrieve; equivalent to id when both are accepted by the handler.
        version: Optional historical profile version to retrieve when querying by client_id."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if profile_id is not None:
            _payload["profile_id"] = profile_id
        if client_id is not None:
            _payload["client_id"] = client_id
        if version is not None:
            _payload["version"] = version
        return self._call("profiling.get_profile", params=_payload, options=options, context=context)

    def list(
        self,
        *,
        client_id: Optional[str] = None,
        status: Optional[str] = None,
        current_only: Optional[bool] = False,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List MiFID II profiles with optional client and status filters

        Returns paginated list of MiFID II profiles. Filterable by client_id, status (active/archived), and current_only flag. Supports limit and offset pagination. Used by the Dashboard profiles management page and by compliance reporting workflows.

        Args:
        current_only: Return only the current active profile for each client."""
        _payload: Dict[str, Any] = {}
        if client_id is not None:
            _payload["client_id"] = client_id
        if status is not None:
            _payload["status"] = status
        if current_only is not None:
            _payload["current_only"] = current_only
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        return self._call("profiling.list", params=_payload, options=options, context=context)

    def questionnaire(
        self,
        *,
        flat: Optional[bool] = False,
        language: Optional[str] = "it",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the MiFID II suitability questionnaire template

        Returns the structured MiFID II investor profiling questionnaire with all sections: investment experience, financial knowledge, risk tolerance, investment objectives, time horizon, and loss capacity. Each question includes type (single choice, multiple choice, slider), options with scores, and regulatory mapping. Used by the Dashboard client onboarding flow to render the questionnaire form.

        Args:
        flat: Return a flat list of questions instead of the full sectioned questionnaire.
        language: Language code used to localize questionnaire labels and help text."""
        _payload: Dict[str, Any] = {}
        if flat is not None:
            _payload["flat"] = flat
        if language is not None:
            _payload["language"] = language
        return self._call("profiling.questionnaire", params=_payload, options=options, context=context)

    def update(
        self,
        *,
        client_id: str,
        questionnaire: Optional[Dict[str, Any]] = None,
        classification: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Update an existing MiFID II profile

        Modifies an existing profile's dimensions, risk category, or metadata. Creates an audit trail entry. Note: typically a new profile is created rather than updating an existing one, to preserve the historical record. Used for corrections.

        Args:
        questionnaire: Partial or complete MiFID questionnaire fields to merge into a new profile version.
        classification: Optional regulatory client classification override for the new profile version."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        if questionnaire is not None:
            _payload["questionnaire"] = questionnaire
        if classification is not None:
            _payload["classification"] = classification
        return self._call("profiling.update", params=_payload, options=options, context=context)

    def validate_answers(
        self,
        *,
        answers: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate questionnaire answers before profile creation

        Validates a set of questionnaire answers against the question schema: checks required fields, valid option values, answer types, and logical consistency. Returns validation result with any errors or warnings. Used as a prerequisite step before profiling.create_profile to catch issues early.

        Args:
        answers: Raw questionnaire answers keyed by question id."""
        _payload: Dict[str, Any] = {}
        _payload["answers"] = answers
        return self._call("profiling.validate_answers", params=_payload, options=options, context=context)



class AsyncProfilingAPI(AsyncBaseAPI):
    """Profiling namespace: archive, check_suitability, convert_answers, create_profile, get_current, get_profile, list, questionnaire, update, validate_answers."""

    async def archive(
        self,
        *,
        id: Optional[str] = None,
        profile_id: Optional[str] = None,
        client_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Archive a MiFID II profile (mark as no longer current)

        Marks a profile as archived, making it no longer the active profile for the linked client. Archived profiles are retained for regulatory record-keeping but excluded from suitability checks. Used when a client completes a new questionnaire.

        Args:
        profile_id: MiFID profile identifier to archive; equivalent to id when both are accepted by the handler."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if profile_id is not None:
            _payload["profile_id"] = profile_id
        if client_id is not None:
            _payload["client_id"] = client_id
        return await self._call("profiling.archive", params=_payload, options=options, context=context)

    async def check_suitability(
        self,
        *,
        client_id: str,
        identifiers: Optional[Union[str, List[str]]] = None,
        portfolio_id: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Check if a security or portfolio is suitable for a client's MiFID II profile

        Evaluates whether a specific security or portfolio allocation is suitable given the client's MiFID II profile. Compares the security's risk level (SRI), complexity, and product type against the client's risk tolerance, knowledge, and investment objectives. Returns: suitable (yes/no), warnings, reasons, and the specific MiFID II constraints that were checked. Required by European regulation before any investment recommendation. Used by the Dashboard recommendation flow and by portfolio rebalancing workflows."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        if identifiers is not None:
            _payload["identifiers"] = identifiers
        if portfolio_id is not None:
            _payload["portfolio_id"] = portfolio_id
        return await self._call("profiling.check_suitability", params=_payload, options=options, context=context)

    async def convert_answers(
        self,
        *,
        answers: Dict[str, Any],
        language: Optional[str] = "it",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Convert raw questionnaire answers into scored profile dimensions

        Transforms raw questionnaire answers into numerical scores across MiFID II dimensions: risk tolerance (1-7), investment horizon, knowledge level, loss capacity, and investment objectives. Each dimension is scored based on the answer weighting scheme. Returns the scored dimensions ready for profile creation. Used as an intermediate step between validation and profile creation.

        Args:
        answers: Raw questionnaire answers keyed by question id.
        language: Language code used for localized score labels in the conversion output."""
        _payload: Dict[str, Any] = {}
        _payload["answers"] = answers
        if language is not None:
            _payload["language"] = language
        return await self._call("profiling.convert_answers", params=_payload, options=options, context=context)

    async def create_profile(
        self,
        *,
        client_id: str,
        questionnaire: Dict[str, Any],
        classification: Optional[str] = "retail",
        visibility: Optional[str] = "private",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Create a MiFID II investor profile from scored dimensions

        Creates a new MiFID II investor profile in the MifidProfiles MongoDB collection. Accepts scored dimensions from profiling.convert_answers and generates: risk profile category (conservative to aggressive), recommended asset allocation ranges, suitability constraints, and regulatory classification. Links to a client entity if client_id is provided. Used by the Dashboard after questionnaire completion.

        Args:
        questionnaire: Scored questionnaire profile generated from profiling.convert_answers.
        classification: Regulatory client classification used for suitability rules.
        visibility: Profile visibility scope."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        _payload["questionnaire"] = questionnaire
        if classification is not None:
            _payload["classification"] = classification
        if visibility is not None:
            _payload["visibility"] = visibility
        return await self._call("profiling.create_profile", params=_payload, options=options, context=context)

    async def get_current(
        self,
        *,
        client_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the current active MiFID II profile for a client

        Returns the most recent active (non-archived) MiFID II profile for a given client. A client may have multiple profiles over time but only one is current. Used by suitability checks to get the applicable profile and by the Dashboard client overview."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        return await self._call("profiling.get_current", params=_payload, options=options, context=context)

    async def get_profile(
        self,
        *,
        id: Optional[str] = None,
        profile_id: Optional[str] = None,
        client_id: Optional[str] = None,
        version: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get a specific MiFID II profile by ID

        Returns the complete MiFID II profile: risk category, scored dimensions, recommended allocations, suitability constraints, creation date, and linked client. Used by the Dashboard profile detail view and by suitability check workflows.

        Args:
        profile_id: MiFID profile identifier to retrieve; equivalent to id when both are accepted by the handler.
        version: Optional historical profile version to retrieve when querying by client_id."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if profile_id is not None:
            _payload["profile_id"] = profile_id
        if client_id is not None:
            _payload["client_id"] = client_id
        if version is not None:
            _payload["version"] = version
        return await self._call("profiling.get_profile", params=_payload, options=options, context=context)

    async def list(
        self,
        *,
        client_id: Optional[str] = None,
        status: Optional[str] = None,
        current_only: Optional[bool] = False,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List MiFID II profiles with optional client and status filters

        Returns paginated list of MiFID II profiles. Filterable by client_id, status (active/archived), and current_only flag. Supports limit and offset pagination. Used by the Dashboard profiles management page and by compliance reporting workflows.

        Args:
        current_only: Return only the current active profile for each client."""
        _payload: Dict[str, Any] = {}
        if client_id is not None:
            _payload["client_id"] = client_id
        if status is not None:
            _payload["status"] = status
        if current_only is not None:
            _payload["current_only"] = current_only
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        return await self._call("profiling.list", params=_payload, options=options, context=context)

    async def questionnaire(
        self,
        *,
        flat: Optional[bool] = False,
        language: Optional[str] = "it",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get the MiFID II suitability questionnaire template

        Returns the structured MiFID II investor profiling questionnaire with all sections: investment experience, financial knowledge, risk tolerance, investment objectives, time horizon, and loss capacity. Each question includes type (single choice, multiple choice, slider), options with scores, and regulatory mapping. Used by the Dashboard client onboarding flow to render the questionnaire form.

        Args:
        flat: Return a flat list of questions instead of the full sectioned questionnaire.
        language: Language code used to localize questionnaire labels and help text."""
        _payload: Dict[str, Any] = {}
        if flat is not None:
            _payload["flat"] = flat
        if language is not None:
            _payload["language"] = language
        return await self._call("profiling.questionnaire", params=_payload, options=options, context=context)

    async def update(
        self,
        *,
        client_id: str,
        questionnaire: Optional[Dict[str, Any]] = None,
        classification: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Update an existing MiFID II profile

        Modifies an existing profile's dimensions, risk category, or metadata. Creates an audit trail entry. Note: typically a new profile is created rather than updating an existing one, to preserve the historical record. Used for corrections.

        Args:
        questionnaire: Partial or complete MiFID questionnaire fields to merge into a new profile version.
        classification: Optional regulatory client classification override for the new profile version."""
        _payload: Dict[str, Any] = {}
        _payload["client_id"] = client_id
        if questionnaire is not None:
            _payload["questionnaire"] = questionnaire
        if classification is not None:
            _payload["classification"] = classification
        return await self._call("profiling.update", params=_payload, options=options, context=context)

    async def validate_answers(
        self,
        *,
        answers: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate questionnaire answers before profile creation

        Validates a set of questionnaire answers against the question schema: checks required fields, valid option values, answer types, and logical consistency. Returns validation result with any errors or warnings. Used as a prerequisite step before profiling.create_profile to catch issues early.

        Args:
        answers: Raw questionnaire answers keyed by question id."""
        _payload: Dict[str, Any] = {}
        _payload["answers"] = answers
        return await self._call("profiling.validate_answers", params=_payload, options=options, context=context)


