"""
Publications API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category publications
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class PublicationsAPI(BaseAPI):
    """Publications namespace: by_source, details, facets, latest, search."""

    def by_source(
        self,
        *,
        source_news_id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get publications by source

        Publications from a specific source.

        Args:
        source_news_id: Source news ID
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["source_news_id"] = source_news_id
        if limit is not None:
            _payload["limit"] = limit
        return self._call("publications.by_source", params=_payload, options=options, context=context, response_format=response_format)

    def details(
        self,
        *,
        doc_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get publication details

        Full publication by ID.

        Args:
        doc_id: Document ID"""
        _payload: Dict[str, Any] = {}
        _payload["doc_id"] = doc_id
        return self._call("publications.details", params=_payload, options=options, context=context)

    def facets(
        self,
        *,
        fields: Optional[List[Any]] = None,
        limit: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get publication facets

        Available sources and types."""
        _payload: Dict[str, Any] = {}
        if fields is not None:
            _payload["fields"] = fields
        if limit is not None:
            _payload["limit"] = limit
        return self._call("publications.facets", params=_payload, options=options, context=context)

    def latest(
        self,
        *,
        language: Optional[str] = None,
        limit: Optional[int] = 20,
        platform: Optional[str] = None,
        status: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get latest publications

        Most recent publications.

        Args:
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if language is not None:
            _payload["language"] = language
        if limit is not None:
            _payload["limit"] = limit
        if platform is not None:
            _payload["platform"] = platform
        if status is not None:
            _payload["status"] = status
        return self._call("publications.latest", params=_payload, options=options, context=context, response_format=response_format)

    def search(
        self,
        *,
        query: str,
        offset: Optional[int] = None,
        order: Optional[str] = None,
        limit: Optional[int] = 20,
        sort: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search publications

        Search research reports and publications.

        Args:
        query: Search query
        limit: Maximum results
        filters: Source/type filters"""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if offset is not None:
            _payload["offset"] = offset
        if order is not None:
            _payload["order"] = order
        if limit is not None:
            _payload["limit"] = limit
        if sort is not None:
            _payload["sort"] = sort
        if filters is not None:
            _payload["filters"] = filters
        return self._call("publications.search", params=_payload, options=options, context=context, response_format=response_format)



class AsyncPublicationsAPI(AsyncBaseAPI):
    """Publications namespace: by_source, details, facets, latest, search."""

    async def by_source(
        self,
        *,
        source_news_id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get publications by source

        Publications from a specific source.

        Args:
        source_news_id: Source news ID
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["source_news_id"] = source_news_id
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("publications.by_source", params=_payload, options=options, context=context, response_format=response_format)

    async def details(
        self,
        *,
        doc_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get publication details

        Full publication by ID.

        Args:
        doc_id: Document ID"""
        _payload: Dict[str, Any] = {}
        _payload["doc_id"] = doc_id
        return await self._call("publications.details", params=_payload, options=options, context=context)

    async def facets(
        self,
        *,
        fields: Optional[List[Any]] = None,
        limit: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get publication facets

        Available sources and types."""
        _payload: Dict[str, Any] = {}
        if fields is not None:
            _payload["fields"] = fields
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("publications.facets", params=_payload, options=options, context=context)

    async def latest(
        self,
        *,
        language: Optional[str] = None,
        limit: Optional[int] = 20,
        platform: Optional[str] = None,
        status: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get latest publications

        Most recent publications.

        Args:
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if language is not None:
            _payload["language"] = language
        if limit is not None:
            _payload["limit"] = limit
        if platform is not None:
            _payload["platform"] = platform
        if status is not None:
            _payload["status"] = status
        return await self._call("publications.latest", params=_payload, options=options, context=context, response_format=response_format)

    async def search(
        self,
        *,
        query: str,
        offset: Optional[int] = None,
        order: Optional[str] = None,
        limit: Optional[int] = 20,
        sort: Optional[str] = None,
        filters: Optional[Dict[str, Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search publications

        Search research reports and publications.

        Args:
        query: Search query
        limit: Maximum results
        filters: Source/type filters"""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if offset is not None:
            _payload["offset"] = offset
        if order is not None:
            _payload["order"] = order
        if limit is not None:
            _payload["limit"] = limit
        if sort is not None:
            _payload["sort"] = sort
        if filters is not None:
            _payload["filters"] = filters
        return await self._call("publications.search", params=_payload, options=options, context=context, response_format=response_format)


