"""
Publications API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category publications
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class PublicationsAPI(BaseAPI):
    """Publications namespace: by_source, details, facets, latest, search."""

    def by_source(
        self,
        *,
        source_news_id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get all publications from a specific institutional source

        Returns all publications from a single source institution identified by its source_news_id. Provides a chronological feed of all content published by one institution. Results include title, date, content type, language, and abstract. Used for building institution-specific research feeds and for tracking a particular institution's published investment views over time. Combine with publications.facets to discover available source_news_id values.

        Args:
        source_news_id: Identifier of the source institution whose publications to return. Discover valid values via publications.facets.
        limit: Maximum number of publications to return."""
        _payload: Dict[str, Any] = {}
        _payload["source_news_id"] = source_news_id
        if limit is not None:
            _payload["limit"] = limit
        return self._call("publications.by_source", params=_payload, options=options, context=context, response_format=response_format)

    def details(
        self,
        *,
        doc_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full publication details and content by document ID

        Retrieves the complete metadata and content for a single institutional publication identified by its document ID. Returns the full title, source institution, author(s), publication date, content type, language, abstract, body text (when available), related securities (TepiloraCodes mentioned in the publication), and links to the original source. Used when a user selects a publication from the search results to read the full content within the Dashboard.

        Args:
        doc_id: Document identifier of the publication to retrieve, as returned by publications.latest, publications.search, or publications.by_source."""
        _payload: Dict[str, Any] = {}
        _payload["doc_id"] = doc_id
        return self._call("publications.details", params=_payload, options=options, context=context)

    def facets(
        self,
        *,
        fields: Optional[List[Any]] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get available publication sources, content types, and languages for filtering

        Returns the aggregated facets (distinct values and counts) for publication metadata fields: sources (which institutions publish content), content types (research report, market outlook, commentary, whitepaper), and languages. Used to populate filter dropdowns and chips in the publications search UI. Enables building a faceted search experience where users can drill down into specific institutions or content types.

        Args:
        fields: Publication metadata fields to aggregate for filter UIs.
        limit: Maximum number of values to return per facet field."""
        _payload: Dict[str, Any] = {}
        if fields is not None:
            _payload["fields"] = fields
        if limit is not None:
            _payload["limit"] = limit
        return self._call("publications.facets", params=_payload, options=options, context=context)

    def latest(
        self,
        *,
        platform: Optional[str] = None,
        language: Optional[str] = None,
        status: Optional[str] = None,
        limit: Optional[int] = 20,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the most recently published research reports and institutional content

        Returns the most recently indexed institutional publications in reverse chronological order. Each entry includes title, source institution, publication date, content type (research report, market outlook, investment commentary, etc.), language, and a brief abstract when available. Filterable by language, platform, and publication status. Used by the Dashboard Publications page for the default latest view and by the AI assistant to surface relevant recent research when answering investment questions.

        Args:
        platform: Optional source platform filter.
        language: Optional ISO 639-1 language filter (e.g. en, it).
        status: Optional publication status filter.
        limit: Maximum number of latest publications to return."""
        _payload: Dict[str, Any] = {}
        if platform is not None:
            _payload["platform"] = platform
        if language is not None:
            _payload["language"] = language
        if status is not None:
            _payload["status"] = status
        if limit is not None:
            _payload["limit"] = limit
        return self._call("publications.latest", params=_payload, options=options, context=context, response_format=response_format)

    def search(
        self,
        *,
        query: Optional[str] = "",
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        sort: Optional[str] = None,
        order: Optional[str] = "desc",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search research reports and institutional publications with full-text and faceted filtering

        Full-text search across the institutional publications database powered by Tantivy search engine. Indexes research reports, market commentary, investment outlooks, and analysis papers from asset managers, research houses, and financial institutions. Supports advanced query syntax, date range filtering, source filtering, publication type filtering, and language filtering. Returns publication title, source, publication date, content type, language, and relevance score. Results are paginated and sortable by date or relevance. Used by the Dashboard Publications page for research discovery and by AI assistants for grounding investment recommendations with institutional research.

        Args:
        filters: Optional structured filters for platform, language, status, or content_type.

        Examples:
            >>> client.publications.search(query='market outlook', limit=5)"""
        _payload: Dict[str, Any] = {}
        if query is not None:
            _payload["query"] = query
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if sort is not None:
            _payload["sort"] = sort
        if order is not None:
            _payload["order"] = order
        return self._call("publications.search", params=_payload, options=options, context=context, response_format=response_format)



class AsyncPublicationsAPI(AsyncBaseAPI):
    """Publications namespace: by_source, details, facets, latest, search."""

    async def by_source(
        self,
        *,
        source_news_id: str,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get all publications from a specific institutional source

        Returns all publications from a single source institution identified by its source_news_id. Provides a chronological feed of all content published by one institution. Results include title, date, content type, language, and abstract. Used for building institution-specific research feeds and for tracking a particular institution's published investment views over time. Combine with publications.facets to discover available source_news_id values.

        Args:
        source_news_id: Identifier of the source institution whose publications to return. Discover valid values via publications.facets.
        limit: Maximum number of publications to return."""
        _payload: Dict[str, Any] = {}
        _payload["source_news_id"] = source_news_id
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("publications.by_source", params=_payload, options=options, context=context, response_format=response_format)

    async def details(
        self,
        *,
        doc_id: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get full publication details and content by document ID

        Retrieves the complete metadata and content for a single institutional publication identified by its document ID. Returns the full title, source institution, author(s), publication date, content type, language, abstract, body text (when available), related securities (TepiloraCodes mentioned in the publication), and links to the original source. Used when a user selects a publication from the search results to read the full content within the Dashboard.

        Args:
        doc_id: Document identifier of the publication to retrieve, as returned by publications.latest, publications.search, or publications.by_source."""
        _payload: Dict[str, Any] = {}
        _payload["doc_id"] = doc_id
        return await self._call("publications.details", params=_payload, options=options, context=context)

    async def facets(
        self,
        *,
        fields: Optional[List[Any]] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get available publication sources, content types, and languages for filtering

        Returns the aggregated facets (distinct values and counts) for publication metadata fields: sources (which institutions publish content), content types (research report, market outlook, commentary, whitepaper), and languages. Used to populate filter dropdowns and chips in the publications search UI. Enables building a faceted search experience where users can drill down into specific institutions or content types.

        Args:
        fields: Publication metadata fields to aggregate for filter UIs.
        limit: Maximum number of values to return per facet field."""
        _payload: Dict[str, Any] = {}
        if fields is not None:
            _payload["fields"] = fields
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("publications.facets", params=_payload, options=options, context=context)

    async def latest(
        self,
        *,
        platform: Optional[str] = None,
        language: Optional[str] = None,
        status: Optional[str] = None,
        limit: Optional[int] = 20,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get the most recently published research reports and institutional content

        Returns the most recently indexed institutional publications in reverse chronological order. Each entry includes title, source institution, publication date, content type (research report, market outlook, investment commentary, etc.), language, and a brief abstract when available. Filterable by language, platform, and publication status. Used by the Dashboard Publications page for the default latest view and by the AI assistant to surface relevant recent research when answering investment questions.

        Args:
        platform: Optional source platform filter.
        language: Optional ISO 639-1 language filter (e.g. en, it).
        status: Optional publication status filter.
        limit: Maximum number of latest publications to return."""
        _payload: Dict[str, Any] = {}
        if platform is not None:
            _payload["platform"] = platform
        if language is not None:
            _payload["language"] = language
        if status is not None:
            _payload["status"] = status
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("publications.latest", params=_payload, options=options, context=context, response_format=response_format)

    async def search(
        self,
        *,
        query: Optional[str] = "",
        filters: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 50,
        offset: Optional[int] = 0,
        sort: Optional[str] = None,
        order: Optional[str] = "desc",
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Search research reports and institutional publications with full-text and faceted filtering

        Full-text search across the institutional publications database powered by Tantivy search engine. Indexes research reports, market commentary, investment outlooks, and analysis papers from asset managers, research houses, and financial institutions. Supports advanced query syntax, date range filtering, source filtering, publication type filtering, and language filtering. Returns publication title, source, publication date, content type, language, and relevance score. Results are paginated and sortable by date or relevance. Used by the Dashboard Publications page for research discovery and by AI assistants for grounding investment recommendations with institutional research.

        Args:
        filters: Optional structured filters for platform, language, status, or content_type.

        Examples:
            >>> await client.publications.search(query='market outlook', limit=5)"""
        _payload: Dict[str, Any] = {}
        if query is not None:
            _payload["query"] = query
        if filters is not None:
            _payload["filters"] = filters
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if sort is not None:
            _payload["sort"] = sort
        if order is not None:
            _payload["order"] = order
        return await self._call("publications.search", params=_payload, options=options, context=context, response_format=response_format)


