"""
Queries API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category queries
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from ._base import AsyncBaseAPI, BaseAPI


class QueriesAPI(BaseAPI):
    """Queries namespace: copy, delete, edit, execute, get, list, preview, save."""

    def copy(
        self,
        *,
        name: str,
        category: str,
        new_name: str,
        description: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Copy query

        Copy query with new name.

        Args:
        name: Source query name
        category: Query category
        new_name: New query name
        description: New description"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        _payload["new_name"] = new_name
        if description is not None:
            _payload["description"] = description
        return self._call("queries.copy", params=_payload, options=options, context=context)

    def delete(
        self,
        *,
        name: str,
        category: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete query

        Delete saved query.

        Args:
        name: Query name
        category: Query category"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        return self._call("queries.delete", params=_payload, options=options, context=context)

    def edit(
        self,
        *,
        name: str,
        category: str,
        definition: Optional[Dict[str, Any]] = None,
        items: Optional[List[Any]] = None,
        expression: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Edit query

        Update existing query.

        Args:
        name: Query name
        category: Query category
        definition: New query definition
        items: New static items
        expression: New expression
        description: New description
        tags: New tags"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        if definition is not None:
            _payload["definition"] = definition
        if items is not None:
            _payload["items"] = items
        if expression is not None:
            _payload["expression"] = expression
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return self._call("queries.edit", params=_payload, options=options, context=context)

    def execute(
        self,
        *,
        id: Optional[str] = None,
        query_id: Optional[str] = None,
        name: Optional[str] = None,
        category: Optional[str] = None,
        output_path: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Execute query

        Execute saved query and return results.

        Args:
        id: Query ID
        query_id: Query ID (alias)
        name: Query name
        category: Query category
        output_path: Output file path"""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if query_id is not None:
            _payload["query_id"] = query_id
        if name is not None:
            _payload["name"] = name
        if category is not None:
            _payload["category"] = category
        if output_path is not None:
            _payload["output_path"] = output_path
        return self._call("queries.execute", params=_payload, options=options, context=context, response_format=response_format)

    def get(
        self,
        *,
        name: str,
        category: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get saved query

        Get query by name.

        Args:
        name: Query name
        category: Query category"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        return self._call("queries.get", params=_payload, options=options, context=context)

    def list(
        self,
        *,
        category: Optional[str] = None,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        order: Optional[str] = None,
        search: Optional[str] = None,
        sort: Optional[str] = None,
        tags: Optional[str] = None,
        type_: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List saved queries

        List user's saved queries.

        Args:
        category: Filter by category
        limit: Maximum results
        offset: Pagination offset"""
        _payload: Dict[str, Any] = {}
        if category is not None:
            _payload["category"] = category
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if order is not None:
            _payload["order"] = order
        if search is not None:
            _payload["search"] = search
        if sort is not None:
            _payload["sort"] = sort
        if tags is not None:
            _payload["tags"] = tags
        if type_ is not None:
            _payload["type"] = type_
        return self._call("queries.list", params=_payload, options=options, context=context)

    def preview(
        self,
        *,
        action: Optional[str] = None,
        category: Optional[str] = None,
        definition: Optional[str] = None,
        expression: Optional[str] = None,
        items: Optional[str] = None,
        params: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 10,
        type_: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Preview query

        Preview query without saving.

        Args:
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if action is not None:
            _payload["action"] = action
        if category is not None:
            _payload["category"] = category
        if definition is not None:
            _payload["definition"] = definition
        if expression is not None:
            _payload["expression"] = expression
        if items is not None:
            _payload["items"] = items
        if params is not None:
            _payload["params"] = params
        if limit is not None:
            _payload["limit"] = limit
        if type_ is not None:
            _payload["type"] = type_
        return self._call("queries.preview", params=_payload, options=options, context=context, response_format=response_format)

    def save(
        self,
        *,
        name: str,
        category: str,
        type_: Optional[str] = "dynamic",
        visibility: Optional[str] = "private",
        definition: Optional[Dict[str, Any]] = None,
        items: Optional[List[Any]] = None,
        expression: Optional[str] = None,
        description: Optional[str] = "",
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Save query

        Save a new query.

        Args:
        name: Query name
        category: Query category
        type_: Query type: dynamic|static|expression
        visibility: Visibility: private|workspace
        definition: Query definition (for dynamic)
        items: Static items (for static)
        expression: Expression (for expression type)
        description: Description
        tags: Tags"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        if type_ is not None:
            _payload["type"] = type_
        if visibility is not None:
            _payload["visibility"] = visibility
        if definition is not None:
            _payload["definition"] = definition
        if items is not None:
            _payload["items"] = items
        if expression is not None:
            _payload["expression"] = expression
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return self._call("queries.save", params=_payload, options=options, context=context)



class AsyncQueriesAPI(AsyncBaseAPI):
    """Queries namespace: copy, delete, edit, execute, get, list, preview, save."""

    async def copy(
        self,
        *,
        name: str,
        category: str,
        new_name: str,
        description: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Copy query

        Copy query with new name.

        Args:
        name: Source query name
        category: Query category
        new_name: New query name
        description: New description"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        _payload["new_name"] = new_name
        if description is not None:
            _payload["description"] = description
        return await self._call("queries.copy", params=_payload, options=options, context=context)

    async def delete(
        self,
        *,
        name: str,
        category: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Delete query

        Delete saved query.

        Args:
        name: Query name
        category: Query category"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        return await self._call("queries.delete", params=_payload, options=options, context=context)

    async def edit(
        self,
        *,
        name: str,
        category: str,
        definition: Optional[Dict[str, Any]] = None,
        items: Optional[List[Any]] = None,
        expression: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Edit query

        Update existing query.

        Args:
        name: Query name
        category: Query category
        definition: New query definition
        items: New static items
        expression: New expression
        description: New description
        tags: New tags"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        if definition is not None:
            _payload["definition"] = definition
        if items is not None:
            _payload["items"] = items
        if expression is not None:
            _payload["expression"] = expression
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return await self._call("queries.edit", params=_payload, options=options, context=context)

    async def execute(
        self,
        *,
        id: Optional[str] = None,
        query_id: Optional[str] = None,
        name: Optional[str] = None,
        category: Optional[str] = None,
        output_path: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Execute query

        Execute saved query and return results.

        Args:
        id: Query ID
        query_id: Query ID (alias)
        name: Query name
        category: Query category
        output_path: Output file path"""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if query_id is not None:
            _payload["query_id"] = query_id
        if name is not None:
            _payload["name"] = name
        if category is not None:
            _payload["category"] = category
        if output_path is not None:
            _payload["output_path"] = output_path
        return await self._call("queries.execute", params=_payload, options=options, context=context, response_format=response_format)

    async def get(
        self,
        *,
        name: str,
        category: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get saved query

        Get query by name.

        Args:
        name: Query name
        category: Query category"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        return await self._call("queries.get", params=_payload, options=options, context=context)

    async def list(
        self,
        *,
        category: Optional[str] = None,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        order: Optional[str] = None,
        search: Optional[str] = None,
        sort: Optional[str] = None,
        tags: Optional[str] = None,
        type_: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List saved queries

        List user's saved queries.

        Args:
        category: Filter by category
        limit: Maximum results
        offset: Pagination offset"""
        _payload: Dict[str, Any] = {}
        if category is not None:
            _payload["category"] = category
        if limit is not None:
            _payload["limit"] = limit
        if offset is not None:
            _payload["offset"] = offset
        if order is not None:
            _payload["order"] = order
        if search is not None:
            _payload["search"] = search
        if sort is not None:
            _payload["sort"] = sort
        if tags is not None:
            _payload["tags"] = tags
        if type_ is not None:
            _payload["type"] = type_
        return await self._call("queries.list", params=_payload, options=options, context=context)

    async def preview(
        self,
        *,
        action: Optional[str] = None,
        category: Optional[str] = None,
        definition: Optional[str] = None,
        expression: Optional[str] = None,
        items: Optional[str] = None,
        params: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 10,
        type_: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Preview query

        Preview query without saving.

        Args:
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if action is not None:
            _payload["action"] = action
        if category is not None:
            _payload["category"] = category
        if definition is not None:
            _payload["definition"] = definition
        if expression is not None:
            _payload["expression"] = expression
        if items is not None:
            _payload["items"] = items
        if params is not None:
            _payload["params"] = params
        if limit is not None:
            _payload["limit"] = limit
        if type_ is not None:
            _payload["type"] = type_
        return await self._call("queries.preview", params=_payload, options=options, context=context, response_format=response_format)

    async def save(
        self,
        *,
        name: str,
        category: str,
        type_: Optional[str] = "dynamic",
        visibility: Optional[str] = "private",
        definition: Optional[Dict[str, Any]] = None,
        items: Optional[List[Any]] = None,
        expression: Optional[str] = None,
        description: Optional[str] = "",
        tags: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Save query

        Save a new query.

        Args:
        name: Query name
        category: Query category
        type_: Query type: dynamic|static|expression
        visibility: Visibility: private|workspace
        definition: Query definition (for dynamic)
        items: Static items (for static)
        expression: Expression (for expression type)
        description: Description
        tags: Tags"""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        _payload["category"] = category
        if type_ is not None:
            _payload["type"] = type_
        if visibility is not None:
            _payload["visibility"] = visibility
        if definition is not None:
            _payload["definition"] = definition
        if items is not None:
            _payload["items"] = items
        if expression is not None:
            _payload["expression"] = expression
        if description is not None:
            _payload["description"] = description
        if tags is not None:
            _payload["tags"] = tags
        return await self._call("queries.save", params=_payload, options=options, context=context)


