"""
Reporting API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category reporting
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from ._base import AsyncBaseAPI, BaseAPI


class ReportingAPI(BaseAPI):
    """Reporting namespace: capabilities, fund_sheet, render, tearsheet, template, templates, themes, validate."""

    def capabilities(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Check available reporting capabilities on this server

        Returns the availability of reporting dependencies: WeasyPrint (PDF generation), Jinja2 (templating), chart libraries, and font availability. Used by the Dashboard to show/hide PDF export options and by health checks."""
        _payload: Dict[str, Any] = {}
        return self._call("reporting.capabilities", params=_payload, options=options, context=context)

    def fund_sheet(
        self,
        *,
        identifier: str,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        risk_free_rate: Optional[float] = 0.0,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Generate a comprehensive fund factsheet for an ETF or mutual fund

        Produces a two-page A4 fund factsheet in HTML or PDF. Automatically fetches all required data: security description, NAV history, performance metrics (YTD, 1Y, 3Y, 5Y), risk metrics (volatility, Sharpe, Sortino, max drawdown), portfolio breakdowns (holdings, sectors, countries), monthly return heatmap, and fee structure. Accepts ISIN (auto-resolves to TepiloraCode) or TepiloraCode directly. Supports 5 locales and custom branding. Phase 1: ETF and Fund types only. Used by the Dashboard fund detail page and by client reporting workflows."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if ai is not None:
            _payload["ai"] = ai
        return self._call("reporting.fund_sheet", params=_payload, options=options, context=context)

    def render(
        self,
        *,
        template: Any,
        data: Optional[Dict[str, Any]] = None,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        params_override: Optional[Dict[str, Any]] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Render an HTML/PDF report from a template with provided data

        Renders a report by combining a Jinja2 template with provided data context. Supports HTML output (self-contained with inline CSS) and optional PDF conversion via WeasyPrint. The data parameter must match the template's data contract. Branding overrides (logo, colors, font) are applied via CSS variables. Supports 5 locales (en, it, fr, es, de) via the locale parameter. Used by the Dashboard for custom report generation and by batch report workflows."""
        _payload: Dict[str, Any] = {}
        _payload["template"] = template
        if data is not None:
            _payload["data"] = data
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if params_override is not None:
            _payload["params_override"] = params_override
        if ai is not None:
            _payload["ai"] = ai
        return self._call("reporting.render", params=_payload, options=options, context=context)

    def tearsheet(
        self,
        *,
        id: Optional[str] = None,
        weights: Optional[Dict[str, Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        benchmark_id: Optional[str] = None,
        benchmark_weights: Optional[Dict[str, Any]] = None,
        benchmark_name: Optional[str] = "Benchmark",
        risk_free_rate: Optional[float] = 0.0,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Build a structured portfolio performance tearsheet payload

        Returns a structured portfolio performance payload: cumulative return series, calendar year returns, monthly return heatmap, risk metrics dashboard block, attribution breakdown, and holdings summary. Accepts either a portfolio `id` (fetches weights from the saved portfolio) or inline `weights`. Supports benchmark overlay via `benchmark_id` or `benchmark_weights`. NOTE: the `format` parameter is accepted for API compatibility but currently ignored — this operation always returns the structured dict, not rendered HTML/PDF. For an HTML tearsheet render, use reporting.render with the 'tearsheet' template."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if weights is not None:
            _payload["weights"] = weights
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if benchmark_id is not None:
            _payload["benchmark_id"] = benchmark_id
        if benchmark_weights is not None:
            _payload["benchmark_weights"] = benchmark_weights
        if benchmark_name is not None:
            _payload["benchmark_name"] = benchmark_name
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if ai is not None:
            _payload["ai"] = ai
        return self._call("reporting.tearsheet", params=_payload, options=options, context=context)

    def template(
        self,
        *,
        name: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get template details and data contract for a specific report template

        Returns the full definition of a report template: name, description, required data fields (data contract), supported parameters, preview thumbnail, and example data. Used by the Dashboard report builder to show what data a template expects and by the AI assistant to explain template requirements."""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        return self._call("reporting.template", params=_payload, options=options, context=context)

    def templates(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List all available report templates

        Returns the catalog of available report templates with names, descriptions, categories (fund_sheet, tearsheet, comparison, market_view), and supported output formats. Used by the Dashboard template selector."""
        _payload: Dict[str, Any] = {}
        return self._call("reporting.templates", params=_payload, options=options, context=context)

    def themes(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available visual themes for reports

        Returns the available visual themes: dark (default Tepilora theme), bright (light background), and any custom themes. Each theme shows color palette, font settings, and a preview. Used by the Dashboard theme selector."""
        _payload: Dict[str, Any] = {}
        return self._call("reporting.themes", params=_payload, options=options, context=context)

    def validate(
        self,
        *,
        template: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate data against a template's data contract

        Checks if provided data matches a template's expected data contract: required fields present, correct types, valid value ranges. Returns validation result with specific errors per field. Used by the Dashboard as a pre-check before rendering and by automated report pipelines."""
        _payload: Dict[str, Any] = {}
        _payload["template"] = template
        return self._call("reporting.validate", params=_payload, options=options, context=context)



class AsyncReportingAPI(AsyncBaseAPI):
    """Reporting namespace: capabilities, fund_sheet, render, tearsheet, template, templates, themes, validate."""

    async def capabilities(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Check available reporting capabilities on this server

        Returns the availability of reporting dependencies: WeasyPrint (PDF generation), Jinja2 (templating), chart libraries, and font availability. Used by the Dashboard to show/hide PDF export options and by health checks."""
        _payload: Dict[str, Any] = {}
        return await self._call("reporting.capabilities", params=_payload, options=options, context=context)

    async def fund_sheet(
        self,
        *,
        identifier: str,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        risk_free_rate: Optional[float] = 0.0,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Generate a comprehensive fund factsheet for an ETF or mutual fund

        Produces a two-page A4 fund factsheet in HTML or PDF. Automatically fetches all required data: security description, NAV history, performance metrics (YTD, 1Y, 3Y, 5Y), risk metrics (volatility, Sharpe, Sortino, max drawdown), portfolio breakdowns (holdings, sectors, countries), monthly return heatmap, and fee structure. Accepts ISIN (auto-resolves to TepiloraCode) or TepiloraCode directly. Supports 5 locales and custom branding. Phase 1: ETF and Fund types only. Used by the Dashboard fund detail page and by client reporting workflows."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if ai is not None:
            _payload["ai"] = ai
        return await self._call("reporting.fund_sheet", params=_payload, options=options, context=context)

    async def render(
        self,
        *,
        template: Any,
        data: Optional[Dict[str, Any]] = None,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        params_override: Optional[Dict[str, Any]] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Render an HTML/PDF report from a template with provided data

        Renders a report by combining a Jinja2 template with provided data context. Supports HTML output (self-contained with inline CSS) and optional PDF conversion via WeasyPrint. The data parameter must match the template's data contract. Branding overrides (logo, colors, font) are applied via CSS variables. Supports 5 locales (en, it, fr, es, de) via the locale parameter. Used by the Dashboard for custom report generation and by batch report workflows."""
        _payload: Dict[str, Any] = {}
        _payload["template"] = template
        if data is not None:
            _payload["data"] = data
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if params_override is not None:
            _payload["params_override"] = params_override
        if ai is not None:
            _payload["ai"] = ai
        return await self._call("reporting.render", params=_payload, options=options, context=context)

    async def tearsheet(
        self,
        *,
        id: Optional[str] = None,
        weights: Optional[Dict[str, Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        benchmark_id: Optional[str] = None,
        benchmark_weights: Optional[Dict[str, Any]] = None,
        benchmark_name: Optional[str] = "Benchmark",
        risk_free_rate: Optional[float] = 0.0,
        locale: Optional[str] = "en",
        output_path: Optional[str] = None,
        ai: Optional[bool] = False,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Build a structured portfolio performance tearsheet payload

        Returns a structured portfolio performance payload: cumulative return series, calendar year returns, monthly return heatmap, risk metrics dashboard block, attribution breakdown, and holdings summary. Accepts either a portfolio `id` (fetches weights from the saved portfolio) or inline `weights`. Supports benchmark overlay via `benchmark_id` or `benchmark_weights`. NOTE: the `format` parameter is accepted for API compatibility but currently ignored — this operation always returns the structured dict, not rendered HTML/PDF. For an HTML tearsheet render, use reporting.render with the 'tearsheet' template."""
        _payload: Dict[str, Any] = {}
        if id is not None:
            _payload["id"] = id
        if weights is not None:
            _payload["weights"] = weights
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if benchmark_id is not None:
            _payload["benchmark_id"] = benchmark_id
        if benchmark_weights is not None:
            _payload["benchmark_weights"] = benchmark_weights
        if benchmark_name is not None:
            _payload["benchmark_name"] = benchmark_name
        if risk_free_rate is not None:
            _payload["risk_free_rate"] = risk_free_rate
        if locale is not None:
            _payload["locale"] = locale
        if output_path is not None:
            _payload["output_path"] = output_path
        if ai is not None:
            _payload["ai"] = ai
        return await self._call("reporting.tearsheet", params=_payload, options=options, context=context)

    async def template(
        self,
        *,
        name: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Get template details and data contract for a specific report template

        Returns the full definition of a report template: name, description, required data fields (data contract), supported parameters, preview thumbnail, and example data. Used by the Dashboard report builder to show what data a template expects and by the AI assistant to explain template requirements."""
        _payload: Dict[str, Any] = {}
        _payload["name"] = name
        return await self._call("reporting.template", params=_payload, options=options, context=context)

    async def templates(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List all available report templates

        Returns the catalog of available report templates with names, descriptions, categories (fund_sheet, tearsheet, comparison, market_view), and supported output formats. Used by the Dashboard template selector."""
        _payload: Dict[str, Any] = {}
        return await self._call("reporting.templates", params=_payload, options=options, context=context)

    async def themes(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List available visual themes for reports

        Returns the available visual themes: dark (default Tepilora theme), bright (light background), and any custom themes. Each theme shows color palette, font settings, and a preview. Used by the Dashboard theme selector."""
        _payload: Dict[str, Any] = {}
        return await self._call("reporting.themes", params=_payload, options=options, context=context)

    async def validate(
        self,
        *,
        template: Dict[str, Any],
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Validate data against a template's data contract

        Checks if provided data matches a template's expected data contract: required fields present, correct types, valid value ranges. Returns validation result with specific errors per field. Used by the Dashboard as a pre-check before rendering and by automated report pipelines."""
        _payload: Dict[str, Any] = {}
        _payload["template"] = template
        return await self._call("reporting.validate", params=_payload, options=options, context=context)


