"""
Search API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category search
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from ._base import AsyncBaseAPI, BaseAPI


class SearchAPI(BaseAPI):
    """Search namespace: global_search."""

    def global_search(
        self,
        *,
        query: str,
        include_recent: Optional[bool] = None,
        limit: Optional[int] = 20,
        types: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Global search

        Search across securities, news, and publications.

        Args:
        query: Search query
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if include_recent is not None:
            _payload["include_recent"] = include_recent
        if limit is not None:
            _payload["limit"] = limit
        if types is not None:
            _payload["types"] = types
        return self._call("search.global", params=_payload, options=options, context=context)



class AsyncSearchAPI(AsyncBaseAPI):
    """Search namespace: global_search."""

    async def global_search(
        self,
        *,
        query: str,
        include_recent: Optional[bool] = None,
        limit: Optional[int] = 20,
        types: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Global search

        Search across securities, news, and publications.

        Args:
        query: Search query
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["query"] = query
        if include_recent is not None:
            _payload["include_recent"] = include_recent
        if limit is not None:
            _payload["limit"] = limit
        if types is not None:
            _payload["types"] = types
        return await self._call("search.global", params=_payload, options=options, context=context)


