"""
Stocks API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category stocks
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class StocksAPI(BaseAPI):
    """Stocks namespace: compare, dividends, indicators, momentum, peers, screen, signals, technicals, valuation."""

    def compare(
        self,
        *,
        identifiers: Union[str, List[str]],
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare stocks

        Compare multiple stocks.

        Args:
        identifiers: List of TepiloraCodes
        metrics: Metrics to compare"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if metrics is not None:
            _payload["metrics"] = metrics
        return self._call("stocks.compare", params=_payload, options=options, context=context, response_format=response_format)

    def dividends(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Dividend data

        Dividend history and yield.

        Args:
        identifier: TepiloraCode or ISIN"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return self._call("stocks.dividends", params=_payload, options=options, context=context, response_format=response_format)

    def indicators(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List indicators

        List available technical indicators."""
        _payload: Dict[str, Any] = {}
        return self._call("stocks.indicators", params=_payload, options=options, context=context)

    def momentum(
        self,
        *,
        identifier: Optional[str] = None,
        lookback_periods: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Momentum analysis

        Calculate momentum indicators.

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        start_date: Start date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if lookback_periods is not None:
            _payload["lookback_periods"] = lookback_periods
        if prices is not None:
            _payload["prices"] = prices
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("stocks.momentum", params=_payload, options=options, context=context, response_format=response_format)

    def peers(
        self,
        *,
        identifier: str,
        limit: Optional[int] = 20,
        metrics: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get peer stocks

        Find peer companies.

        Args:
        identifier: TepiloraCode or ISIN
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if limit is not None:
            _payload["limit"] = limit
        if metrics is not None:
            _payload["metrics"] = metrics
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("stocks.peers", params=_payload, options=options, context=context, response_format=response_format)

    def screen(
        self,
        *,
        rank_by: Optional[str] = None,
        start_date: Optional[str] = None,
        universe: Optional[Dict[str, Any]] = None,
        criteria: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen stocks

        Screen stocks by technical criteria.

        Args:
        universe: Universe filters
        criteria: Screening criteria
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if rank_by is not None:
            _payload["rank_by"] = rank_by
        if start_date is not None:
            _payload["start_date"] = start_date
        if universe is not None:
            _payload["universe"] = universe
        if criteria is not None:
            _payload["criteria"] = criteria
        if limit is not None:
            _payload["limit"] = limit
        return self._call("stocks.screen", params=_payload, options=options, context=context, response_format=response_format)

    def signals(
        self,
        *,
        identifier: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        strategies: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Trading signals

        Generate trading signals.

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        strategies: Signal strategies to apply
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if prices is not None:
            _payload["prices"] = prices
        if strategies is not None:
            _payload["strategies"] = strategies
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        return self._call("stocks.signals", params=_payload, options=options, context=context, response_format=response_format)

    def technicals(
        self,
        *,
        bb_period: Optional[str] = None,
        bb_std: Optional[str] = None,
        ema_periods: Optional[str] = None,
        identifier: Optional[str] = None,
        macd_fast: Optional[str] = None,
        macd_signal: Optional[str] = None,
        macd_slow: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        indicators: Optional[List[Any]] = None,
        rsi_period: Optional[str] = None,
        sma_periods: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Technical indicators

        Calculate technical indicators (SMA, RSI, MACD, etc.).

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        indicators: Indicators to calculate
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if bb_period is not None:
            _payload["bb_period"] = bb_period
        if bb_std is not None:
            _payload["bb_std"] = bb_std
        if ema_periods is not None:
            _payload["ema_periods"] = ema_periods
        if identifier is not None:
            _payload["identifier"] = identifier
        if macd_fast is not None:
            _payload["macd_fast"] = macd_fast
        if macd_signal is not None:
            _payload["macd_signal"] = macd_signal
        if macd_slow is not None:
            _payload["macd_slow"] = macd_slow
        if prices is not None:
            _payload["prices"] = prices
        if indicators is not None:
            _payload["indicators"] = indicators
        if rsi_period is not None:
            _payload["rsi_period"] = rsi_period
        if sma_periods is not None:
            _payload["sma_periods"] = sma_periods
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        return self._call("stocks.technicals", params=_payload, options=options, context=context, response_format=response_format)

    def valuation(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Valuation metrics

        PE, PB, EV/EBITDA, etc.

        Args:
        identifier: TepiloraCode or ISIN"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return self._call("stocks.valuation", params=_payload, options=options, context=context, response_format=response_format)



class AsyncStocksAPI(AsyncBaseAPI):
    """Stocks namespace: compare, dividends, indicators, momentum, peers, screen, signals, technicals, valuation."""

    async def compare(
        self,
        *,
        identifiers: Union[str, List[str]],
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare stocks

        Compare multiple stocks.

        Args:
        identifiers: List of TepiloraCodes
        metrics: Metrics to compare"""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if metrics is not None:
            _payload["metrics"] = metrics
        return await self._call("stocks.compare", params=_payload, options=options, context=context, response_format=response_format)

    async def dividends(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Dividend data

        Dividend history and yield.

        Args:
        identifier: TepiloraCode or ISIN"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return await self._call("stocks.dividends", params=_payload, options=options, context=context, response_format=response_format)

    async def indicators(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """List indicators

        List available technical indicators."""
        _payload: Dict[str, Any] = {}
        return await self._call("stocks.indicators", params=_payload, options=options, context=context)

    async def momentum(
        self,
        *,
        identifier: Optional[str] = None,
        lookback_periods: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Momentum analysis

        Calculate momentum indicators.

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        start_date: Start date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if lookback_periods is not None:
            _payload["lookback_periods"] = lookback_periods
        if prices is not None:
            _payload["prices"] = prices
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("stocks.momentum", params=_payload, options=options, context=context, response_format=response_format)

    async def peers(
        self,
        *,
        identifier: str,
        limit: Optional[int] = 20,
        metrics: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get peer stocks

        Find peer companies.

        Args:
        identifier: TepiloraCode or ISIN
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if limit is not None:
            _payload["limit"] = limit
        if metrics is not None:
            _payload["metrics"] = metrics
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("stocks.peers", params=_payload, options=options, context=context, response_format=response_format)

    async def screen(
        self,
        *,
        rank_by: Optional[str] = None,
        start_date: Optional[str] = None,
        universe: Optional[Dict[str, Any]] = None,
        criteria: Optional[Dict[str, Any]] = None,
        limit: Optional[int] = 50,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen stocks

        Screen stocks by technical criteria.

        Args:
        universe: Universe filters
        criteria: Screening criteria
        limit: Maximum results"""
        _payload: Dict[str, Any] = {}
        if rank_by is not None:
            _payload["rank_by"] = rank_by
        if start_date is not None:
            _payload["start_date"] = start_date
        if universe is not None:
            _payload["universe"] = universe
        if criteria is not None:
            _payload["criteria"] = criteria
        if limit is not None:
            _payload["limit"] = limit
        return await self._call("stocks.screen", params=_payload, options=options, context=context, response_format=response_format)

    async def signals(
        self,
        *,
        identifier: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        strategies: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Trading signals

        Generate trading signals.

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        strategies: Signal strategies to apply
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if prices is not None:
            _payload["prices"] = prices
        if strategies is not None:
            _payload["strategies"] = strategies
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        return await self._call("stocks.signals", params=_payload, options=options, context=context, response_format=response_format)

    async def technicals(
        self,
        *,
        bb_period: Optional[str] = None,
        bb_std: Optional[str] = None,
        ema_periods: Optional[str] = None,
        identifier: Optional[str] = None,
        macd_fast: Optional[str] = None,
        macd_signal: Optional[str] = None,
        macd_slow: Optional[str] = None,
        prices: Optional[Dict[str, Any]] = None,
        indicators: Optional[List[Any]] = None,
        rsi_period: Optional[str] = None,
        sma_periods: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Technical indicators

        Calculate technical indicators (SMA, RSI, MACD, etc.).

        Args:
        identifier: TepiloraCode or ISIN
        prices: User-provided prices
        indicators: Indicators to calculate
        start_date: Start date (YYYY-MM-DD)
        end_date: End date (YYYY-MM-DD)"""
        _payload: Dict[str, Any] = {}
        if bb_period is not None:
            _payload["bb_period"] = bb_period
        if bb_std is not None:
            _payload["bb_std"] = bb_std
        if ema_periods is not None:
            _payload["ema_periods"] = ema_periods
        if identifier is not None:
            _payload["identifier"] = identifier
        if macd_fast is not None:
            _payload["macd_fast"] = macd_fast
        if macd_signal is not None:
            _payload["macd_signal"] = macd_signal
        if macd_slow is not None:
            _payload["macd_slow"] = macd_slow
        if prices is not None:
            _payload["prices"] = prices
        if indicators is not None:
            _payload["indicators"] = indicators
        if rsi_period is not None:
            _payload["rsi_period"] = rsi_period
        if sma_periods is not None:
            _payload["sma_periods"] = sma_periods
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        return await self._call("stocks.technicals", params=_payload, options=options, context=context, response_format=response_format)

    async def valuation(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Valuation metrics

        PE, PB, EV/EBITDA, etc.

        Args:
        identifier: TepiloraCode or ISIN"""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return await self._call("stocks.valuation", params=_payload, options=options, context=context, response_format=response_format)


