"""
Stocks API namespace.

AUTO-GENERATED by scripts/generate_sdk.py - DO NOT EDIT MANUALLY!
Regenerate with: python scripts/generate_sdk.py --category stocks
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import AsyncBaseAPI, BaseAPI


class StocksAPI(BaseAPI):
    """Stocks namespace: compare, dividends, indicators, momentum, peers, screen, signals, technicals, valuation."""

    def compare(
        self,
        *,
        identifiers: Union[str, List[str]],
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple stocks side by side across key metrics

        Returns a comparison table for 2 or more stocks across: price performance (1M/3M/6M/1Y), valuation (PE, PB, dividend yield), fundamentals (margins, ROE, revenue growth), and technicals (RSI, momentum score). Each metric shows the value per stock plus a ranking. Used by the Dashboard stock comparison view."""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if metrics is not None:
            _payload["metrics"] = metrics
        return self._call("stocks.compare", params=_payload, options=options, context=context, response_format=response_format)

    def dividends(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get dividend history, yield, and payout analysis for a stock

        Returns dividend history (payment dates, amounts, ex-dates), current dividend yield, payout ratio, dividend growth rate (1Y/3Y/5Y CAGR), and streak (consecutive years of dividend payments/increases). Used by the Dashboard dividend analysis tab and by income-focused screening strategies."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return self._call("stocks.dividends", params=_payload, options=options, context=context, response_format=response_format)

    def indicators(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Catalog of available technical indicator definitions

        Returns the static catalog of technical indicators the library knows how to compute, grouped by category: trend (SMA, EMA, MACD), momentum (RSI, ROC), volatility (Bollinger Bands, ATR), volume (OBV). Each entry carries the indicator name, category, default parameters, and a short description. NOTE: this operation takes no identifier and returns no per-stock values — to compute indicators for a specific stock, use stocks.technicals. Used by the Dashboard indicator picker and by the AI assistant to answer 'what indicators do you support'."""
        _payload: Dict[str, Any] = {}
        return self._call("stocks.indicators", params=_payload, options=options, context=context)

    def momentum(
        self,
        *,
        identifier: Optional[str] = None,
        lookback_periods: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        prices: Optional[Any] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate price momentum scores and signals for stocks

        Computes momentum indicators: absolute momentum (returns over 1M, 3M, 6M, 12M periods), relative momentum (vs. benchmark or peer group), momentum score (composite ranking), and trend strength indicators. Used by momentum-based screening strategies and by the Dashboard momentum analysis view."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if lookback_periods is not None:
            _payload["lookback_periods"] = lookback_periods
        if start_date is not None:
            _payload["start_date"] = start_date
        if prices is not None:
            _payload["prices"] = prices
        return self._call("stocks.momentum", params=_payload, options=options, context=context, response_format=response_format)

    def peers(
        self,
        *,
        identifier: str,
        metrics: Optional[List[Any]] = None,
        limit: Optional[int] = 20,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Find peer companies in the same sector and industry

        Identifies peer companies for a given stock based on sector, industry, market cap tier, and geographic region. Returns peer list with key comparison metrics: market cap, PE, revenue, margins, and performance. Used by the Dashboard peers comparison tab and by relative valuation workflows."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if metrics is not None:
            _payload["metrics"] = metrics
        if limit is not None:
            _payload["limit"] = limit
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("stocks.peers", params=_payload, options=options, context=context, response_format=response_format)

    def screen(
        self,
        *,
        universe: Optional[Dict[str, Any]] = None,
        criteria: Optional[Dict[str, Any]] = None,
        rank_by: Optional[str] = None,
        limit: Optional[int] = 50,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen stocks by technical and fundamental criteria

        Filters the stock universe by combined technical (RSI range, MA crossover, MACD signal) and fundamental (PE ratio, market cap, dividend yield) criteria. Returns stocks matching all criteria with their current indicator values. Used by the Dashboard stock screener."""
        _payload: Dict[str, Any] = {}
        if universe is not None:
            _payload["universe"] = universe
        if criteria is not None:
            _payload["criteria"] = criteria
        if rank_by is not None:
            _payload["rank_by"] = rank_by
        if limit is not None:
            _payload["limit"] = limit
        if start_date is not None:
            _payload["start_date"] = start_date
        return self._call("stocks.screen", params=_payload, options=options, context=context, response_format=response_format)

    def signals(
        self,
        *,
        identifier: Optional[str] = None,
        strategies: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        prices: Optional[Any] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Generate buy/sell/hold signals from technical indicators

        Produces consolidated trading signals from multiple technical indicators: MA crossover signals, RSI overbought/oversold, MACD crossover, Bollinger Band breakout, and volume confirmation. Each signal includes direction (buy/sell/hold), strength (strong/moderate/weak), and the contributing indicators. Used by the Dashboard signal summary and by alert rule conditions."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if strategies is not None:
            _payload["strategies"] = strategies
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if prices is not None:
            _payload["prices"] = prices
        return self._call("stocks.signals", params=_payload, options=options, context=context, response_format=response_format)

    def technicals(
        self,
        *,
        identifier: Optional[str] = None,
        indicators: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        prices: Optional[Any] = None,
        sma_periods: Optional[List[Any]] = None,
        ema_periods: Optional[List[Any]] = None,
        rsi_period: Optional[int] = 14,
        macd_fast: Optional[int] = 12,
        macd_slow: Optional[int] = 26,
        macd_signal: Optional[int] = 9,
        bb_period: Optional[int] = 20,
        bb_std: Optional[int] = 2,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate technical analysis indicators for a stock or ETF

        Computes standard technical analysis indicators from price history: moving averages (SMA, EMA, WMA for configurable periods), RSI (Relative Strength Index), MACD (Moving Average Convergence Divergence with signal and histogram), Bollinger Bands, ATR (Average True Range), Stochastic Oscillator, and OBV (On-Balance Volume). Accepts TepiloraCode or user-provided price data. Used by the Dashboard technical analysis view and by algorithmic screening workflows."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if indicators is not None:
            _payload["indicators"] = indicators
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if prices is not None:
            _payload["prices"] = prices
        if sma_periods is not None:
            _payload["sma_periods"] = sma_periods
        if ema_periods is not None:
            _payload["ema_periods"] = ema_periods
        if rsi_period is not None:
            _payload["rsi_period"] = rsi_period
        if macd_fast is not None:
            _payload["macd_fast"] = macd_fast
        if macd_slow is not None:
            _payload["macd_slow"] = macd_slow
        if macd_signal is not None:
            _payload["macd_signal"] = macd_signal
        if bb_period is not None:
            _payload["bb_period"] = bb_period
        if bb_std is not None:
            _payload["bb_std"] = bb_std
        return self._call("stocks.technicals", params=_payload, options=options, context=context, response_format=response_format)

    def valuation(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate valuation metrics and fair value estimates for a stock

        Computes relative valuation metrics: PE, PB, PS, PCF, EV/EBITDA, dividend yield, PEG ratio — compared against sector medians and historical averages. Includes a simple DCF fair value estimate when sufficient fundamental data is available. Returns current vs. historical percentile for each metric. Used by the Dashboard valuation tab and by the AI assistant for valuation context."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return self._call("stocks.valuation", params=_payload, options=options, context=context, response_format=response_format)



class AsyncStocksAPI(AsyncBaseAPI):
    """Stocks namespace: compare, dividends, indicators, momentum, peers, screen, signals, technicals, valuation."""

    async def compare(
        self,
        *,
        identifiers: Union[str, List[str]],
        metrics: Optional[List[Any]] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Compare multiple stocks side by side across key metrics

        Returns a comparison table for 2 or more stocks across: price performance (1M/3M/6M/1Y), valuation (PE, PB, dividend yield), fundamentals (margins, ROE, revenue growth), and technicals (RSI, momentum score). Each metric shows the value per stock plus a ranking. Used by the Dashboard stock comparison view."""
        _payload: Dict[str, Any] = {}
        _payload["identifiers"] = identifiers
        if metrics is not None:
            _payload["metrics"] = metrics
        return await self._call("stocks.compare", params=_payload, options=options, context=context, response_format=response_format)

    async def dividends(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Get dividend history, yield, and payout analysis for a stock

        Returns dividend history (payment dates, amounts, ex-dates), current dividend yield, payout ratio, dividend growth rate (1Y/3Y/5Y CAGR), and streak (consecutive years of dividend payments/increases). Used by the Dashboard dividend analysis tab and by income-focused screening strategies."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return await self._call("stocks.dividends", params=_payload, options=options, context=context, response_format=response_format)

    async def indicators(
        self,
        *,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Catalog of available technical indicator definitions

        Returns the static catalog of technical indicators the library knows how to compute, grouped by category: trend (SMA, EMA, MACD), momentum (RSI, ROC), volatility (Bollinger Bands, ATR), volume (OBV). Each entry carries the indicator name, category, default parameters, and a short description. NOTE: this operation takes no identifier and returns no per-stock values — to compute indicators for a specific stock, use stocks.technicals. Used by the Dashboard indicator picker and by the AI assistant to answer 'what indicators do you support'."""
        _payload: Dict[str, Any] = {}
        return await self._call("stocks.indicators", params=_payload, options=options, context=context)

    async def momentum(
        self,
        *,
        identifier: Optional[str] = None,
        lookback_periods: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        prices: Optional[Any] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate price momentum scores and signals for stocks

        Computes momentum indicators: absolute momentum (returns over 1M, 3M, 6M, 12M periods), relative momentum (vs. benchmark or peer group), momentum score (composite ranking), and trend strength indicators. Used by momentum-based screening strategies and by the Dashboard momentum analysis view."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if lookback_periods is not None:
            _payload["lookback_periods"] = lookback_periods
        if start_date is not None:
            _payload["start_date"] = start_date
        if prices is not None:
            _payload["prices"] = prices
        return await self._call("stocks.momentum", params=_payload, options=options, context=context, response_format=response_format)

    async def peers(
        self,
        *,
        identifier: str,
        metrics: Optional[List[Any]] = None,
        limit: Optional[int] = 20,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Find peer companies in the same sector and industry

        Identifies peer companies for a given stock based on sector, industry, market cap tier, and geographic region. Returns peer list with key comparison metrics: market cap, PE, revenue, margins, and performance. Used by the Dashboard peers comparison tab and by relative valuation workflows."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        if metrics is not None:
            _payload["metrics"] = metrics
        if limit is not None:
            _payload["limit"] = limit
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("stocks.peers", params=_payload, options=options, context=context, response_format=response_format)

    async def screen(
        self,
        *,
        universe: Optional[Dict[str, Any]] = None,
        criteria: Optional[Dict[str, Any]] = None,
        rank_by: Optional[str] = None,
        limit: Optional[int] = 50,
        start_date: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Screen stocks by technical and fundamental criteria

        Filters the stock universe by combined technical (RSI range, MA crossover, MACD signal) and fundamental (PE ratio, market cap, dividend yield) criteria. Returns stocks matching all criteria with their current indicator values. Used by the Dashboard stock screener."""
        _payload: Dict[str, Any] = {}
        if universe is not None:
            _payload["universe"] = universe
        if criteria is not None:
            _payload["criteria"] = criteria
        if rank_by is not None:
            _payload["rank_by"] = rank_by
        if limit is not None:
            _payload["limit"] = limit
        if start_date is not None:
            _payload["start_date"] = start_date
        return await self._call("stocks.screen", params=_payload, options=options, context=context, response_format=response_format)

    async def signals(
        self,
        *,
        identifier: Optional[str] = None,
        strategies: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        prices: Optional[Any] = None,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Generate buy/sell/hold signals from technical indicators

        Produces consolidated trading signals from multiple technical indicators: MA crossover signals, RSI overbought/oversold, MACD crossover, Bollinger Band breakout, and volume confirmation. Each signal includes direction (buy/sell/hold), strength (strong/moderate/weak), and the contributing indicators. Used by the Dashboard signal summary and by alert rule conditions."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if strategies is not None:
            _payload["strategies"] = strategies
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if prices is not None:
            _payload["prices"] = prices
        return await self._call("stocks.signals", params=_payload, options=options, context=context, response_format=response_format)

    async def technicals(
        self,
        *,
        identifier: Optional[str] = None,
        indicators: Optional[List[Any]] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        prices: Optional[Any] = None,
        sma_periods: Optional[List[Any]] = None,
        ema_periods: Optional[List[Any]] = None,
        rsi_period: Optional[int] = 14,
        macd_fast: Optional[int] = 12,
        macd_slow: Optional[int] = 26,
        macd_signal: Optional[int] = 9,
        bb_period: Optional[int] = 20,
        bb_std: Optional[int] = 2,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate technical analysis indicators for a stock or ETF

        Computes standard technical analysis indicators from price history: moving averages (SMA, EMA, WMA for configurable periods), RSI (Relative Strength Index), MACD (Moving Average Convergence Divergence with signal and histogram), Bollinger Bands, ATR (Average True Range), Stochastic Oscillator, and OBV (On-Balance Volume). Accepts TepiloraCode or user-provided price data. Used by the Dashboard technical analysis view and by algorithmic screening workflows."""
        _payload: Dict[str, Any] = {}
        if identifier is not None:
            _payload["identifier"] = identifier
        if indicators is not None:
            _payload["indicators"] = indicators
        if start_date is not None:
            _payload["start_date"] = start_date
        if end_date is not None:
            _payload["end_date"] = end_date
        if prices is not None:
            _payload["prices"] = prices
        if sma_periods is not None:
            _payload["sma_periods"] = sma_periods
        if ema_periods is not None:
            _payload["ema_periods"] = ema_periods
        if rsi_period is not None:
            _payload["rsi_period"] = rsi_period
        if macd_fast is not None:
            _payload["macd_fast"] = macd_fast
        if macd_slow is not None:
            _payload["macd_slow"] = macd_slow
        if macd_signal is not None:
            _payload["macd_signal"] = macd_signal
        if bb_period is not None:
            _payload["bb_period"] = bb_period
        if bb_std is not None:
            _payload["bb_std"] = bb_std
        return await self._call("stocks.technicals", params=_payload, options=options, context=context, response_format=response_format)

    async def valuation(
        self,
        *,
        identifier: str,
        options: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
        response_format: Optional[str] = None,
    ) -> Any:
        """Calculate valuation metrics and fair value estimates for a stock

        Computes relative valuation metrics: PE, PB, PS, PCF, EV/EBITDA, dividend yield, PEG ratio — compared against sector medians and historical averages. Includes a simple DCF fair value estimate when sufficient fundamental data is available. Returns current vs. historical percentile for each metric. Used by the Dashboard valuation tab and by the AI assistant for valuation context."""
        _payload: Dict[str, Any] = {}
        _payload["identifier"] = identifier
        return await self._call("stocks.valuation", params=_payload, options=options, context=context, response_format=response_format)


